### ISSUE TITLE
decks/subdecks

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#10]
I use about 300 decks / subdecks in up to 5 depth levels.

Could not this screen use the concept of hierarchy?
As it does not hierarchize in nodes, alphabetic ordering means you have to keep looking for the subdeck between 300 decks.

![image](https://user-images.githubusercontent.com/42243532/54117348-4bc4f100-43cf-11e9-8d0d-9b519c21a412.png)

**VS**

![image](https://user-images.githubusercontent.com/42243532/54117518-b6762c80-43cf-11e9-9aa2-82856cae4221.png)

**Comment by fonol** [comment]
I see, if you got that many subdecks, the selection might prove quite unusable. There definitely needs to be some sort of expanding/collapsing.

**Comment by cjdduarte** [comment]
It would help a lot. thank you.
Congratulations again for the addon.

**Comment by fonol** [comment]
It is implemented, but I still have to test it a bit, might update tomorrow evening.

**Comment by cjdduarte** [comment]
I saw that he implemented the collapse. Maybe in it would put it to the left of the text (Anki standard), but it's just a detail. Thanks.
