### ISSUE TITLE
is this bug? 

### ISSUE THREAD

**Issue by drsnn** [fonol/anki-search-inside-add-card#100]
i am sorry if I am writing wrong place. I have problem after last update. I cannot import cvs files properly and get this:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-20 03:10:35

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 34, in cmd
  File "aqt/webview.py", line 114, in _onCmd
  File "aqt/webview.py", line 512, in _onBridgeCmd
TypeError: cannot unpack non-iterable NoneType object

Thank you very much

**Comment by fonol** [comment]
Hi, are you sure it is this add-on? Does the error occur with only this add-on enabled, and go away if you disable it?

**Comment by drsnn** [comment]
Hi Fonol. 

After i closed and opened app, it is go away, now it is working normal. 

Thank you very much for all your efforts. Everyday i thanks to you for this awesome addon.
