### ISSUE TITLE
Copy pasting text from PDF to a field results in the pasted text being white text on black backround

### ISSUE THREAD

**Issue by An-png** [fonol/anki-search-inside-add-card#101]
![black background problem](https://user-images.githubusercontent.com/61632895/82735717-3d809d80-9d13-11ea-98b7-7811062b3251.png)

This is how pasted text is formatted. 

It is a mild annoyance, as you can simply change the background to white and the text to black. However, if you chose another colour in the colour palette (for example, you wanted to make some text red), then you would have to constantly switch back and forth the red colour and black colour in the palette.

**Comment by fonol** [comment]
Have you checked "Paste without Shift strips formatting" in Anki's preferences?

**Comment by An-png** [comment]
Could this be mentioned at the top of the add-on page on Ankiweb?
