### ISSUE TITLE
why i don't enable search when typing in new card, it still do it

### ISSUE THREAD

**Issue by fitzlm** [fonol/anki-search-inside-add-card#102]
I don't want this add on show search result when i typing in the front of a card, it bothers me and it seems to consume performance.

The following snippets is my conifg info.
{
    "addonNoteDBFolderPath": "",
    "alwaysRebuildIndexIfSmallerThan": 1500,
    "decks": [],
    "delayWhileTyping": 1000,
    "fieldsToExclude": {},
    "fieldsToHideInResults": {},
    "gridView": false,
    "hideSidebar": false,
    "highlighting": true,
    "imageMaxHeight": 100,
    "leftSideWidthInPercent": 40,
    "logging": false,
    "noteScale": 1.0,
    "notes.queue.missedNotesHandling": "remove-schedule",
    "notes.queue.priorityScaleFactor": 5,
    "notes.queue.scheduleDialogOnDoneUnscheduledNotes": false,
    "notes.showSource": true,
    "notes.sidebar.visible": false,
    "numberOfResults": 1000,
    "pdf.clozegen.field.clozedtext": "",
    "pdf.clozegen.field.page": "",
    "pdf.clozegen.field.pdfpath": "",
    "pdf.clozegen.field.pdftitle": "",
    "pdf.clozegen.notetype": "",
    "pdf.import.folders_to_search": [],
    "pdf.onOpen.autoFillFieldsWithPDFName": [],
    "pdf.onOpen.autoFillTagsWithPDFsTags": true,
    "pdf.queue.hide": false,
    "pdf.theme": "pdf_reader.css",
    "pdfTooltipMaxHeight": 300,
    "pdfTooltipMaxWidth": 350,
    "pdfTooltipResultLimit": 50,
    "pdfUrlImportSavePath": "",
    "removeDivsFromOutput": false,
    "renderImmediately": true,
    "searchOnSelection": false,
    "searchOnTagEntry": true,
    "searchOnTyping": false,
    "searchUrls": [
        "https://en.wikipedia.org/w/index.php?search=[QUERY]&title=Special%3ASearch&go=Go&ns0=1"
    ],
    "searchpane.zoom": 1.0,
    "showRetentionScores": true,
    "showTagInfoOnHover": true,
    "showTimeline": true,
    "stopwords": [
        "me",
        "my",
        "myself",
        "we",
        "our",
        "ours",
        "ourselves",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "he",
        "him",
        "his",
        "himself",
        "she",
        "her",
        "hers",
        "herself",
        "it",
        "its",
        "itself",
        "they",
        "them",
        "their",
        "theirs",
        "themselves",
        "what",
        "which",
        "who",
        "whom",
        "this",
        "that",
        "these",
        "those",
        "am",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "having",
        "do",
        "does",
        "did",
        "doing",
        "a",
        "an",
        "the",
        "and",
        "but",
        "if",
        "or",
        "because",
        "as",
        "until",
        "while",
        "of",
        "at",
        "by",
        "for",
        "with",
        "about",
        "against",
        "between",
        "into",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "to",
        "from",
        "up",
        "down",
        "in",
        "out",
        "on",
        "off",
        "over",
        "under",
        "again",
        "further",
        "then",
        "once",
        "here",
        "there",
        "when",
        "where",
        "why",
        "how",
        "all",
        "any",
        "both",
        "each",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "no",
        "nor",
        "not",
        "only",
        "own",
        "same",
        "so",
        "than",
        "too",
        "very",
        "can",
        "will",
        "just",
        "done",
        "should",
        "no"
    ],
    "styling": {
        "bottomBar": {
            "browserSearchInputBackgroundColor": "white",
            "browserSearchInputBorderColor": "grey",
            "browserSearchInputForegroundColor": "black",
            "selectBackgroundColor": "white",
            "selectForegroundColor": "black",
            "timelineBoxBackgroundColor": "#595959",
            "timelineBoxBorderColor": "#595959"
        },
        "general": {
            "buttonBackgroundColor": "white",
            "buttonBorderColor": "#404040",
            "buttonForegroundColor": "#404040",
            "fieldSeparatorColor": "#2496dc",
            "highlightBackgroundColor": "yellow",
            "highlightForegroundColor": "black",
            "keywordColor": "#2496dc",
            "noteBackgroundColor": "white",
            "noteBorderColor": "lightseagreen",
            "noteFontSize": 12,
            "noteForegroundColor": "black",
            "noteHoverBorderColor": "#2496dc",
            "rankingLabelBackgroundColor": "lightseagreen",
            "rankingLabelForegroundColor": "white",
            "tagBackgroundColor": "#f0506e",
            "tagFontSize": 12,
            "tagForegroundColor": "white",
            "windowColumnSeparatorColor": "lightseagreen"
        },
        "modal": {
            "modalBackgroundColor": "white",
            "modalBorderColor": "#2496dc",
            "modalForegroundColor": "black",
            "stripedTableBackgroundColor": "#f2f2f2"
        },
        "topBar": {
            "deckSelectBackgroundColor": "white",
            "deckSelectButtonBackgroundColor": "white",
            "deckSelectButtonBorderColor": "grey",
            "deckSelectButtonForegroundColor": "grey",
            "deckSelectCheckmarkColor": "green",
            "deckSelectFontSize": 11,
            "deckSelectForegroundColor": "black",
            "deckSelectHoverBackgroundColor": "#5f6468",
            "deckSelectHoverForegroundColor": "white"
        }
    },
    "switchLeftRight": false,
    "synonyms": [],
    "tagClickShouldSearch": true,
    "tagHoverDelayInMiliSec": 1000,
    "toggleShortcut": "Ctrl+F",
    "useFTS": true,
    "useInEdit": false,
    "usePorterStemmer": false,
    "userNotesPerDay": 5
}

**Comment by fonol** [comment]
I tested on two machines, it works for me. Does the error persist with other add-ons disabled?

**Comment by fitzlm** [comment]
@fonol yes,  i tested, when the plugin area displays content, adding the first card will not refresh the content displayed on the right, but when I continue to add it, it will be as you type (you can try to enter only one commonly used word first )Refresh search results.
I hope it doesn't search automatically, but search when I trigger the search button.

**Comment by fonol** [comment]
Hi, you were right. The error occurs after you add a card. I updated the add-on with a fix. Please tell me if it is working now for you.

**Comment by fitzlm** [comment]
@fonol  You're really amazing, you solved the problem so quickly, I'm sorry to reply to you so late，you really did a great job, very thanks!

**Comment by fonol** [comment]
No problem mate, thanks for the report.
