### ISSUE TITLE
Add explanation when note creation fails

### ISSUE THREAD

**Issue by ShaddyDC** [fonol/anki-search-inside-add-card#103]
Firstly, I love this addon. I'm still in the process of finding my way around though, and one thing that threw me off today was that when you try to add a pdf (as opposed to a website which I'm normally doing), you also have to put in a title. 

It makes sense in hindsight, but I had kind of assumed the "Title" field to only belong together with the "Text" field, especially since I had already given the pdf file a name through "PDF from Webpage".
So, I was hitting "Create" for a couple of minutes without understanding why it didn't do anything. It would be nice if it could give some indication of why it won't create the note. It's no biggie, and I'm now aware of it, but others could probably run into it as well, especially if they're not thinking about it too deeply. 

Adding this would make things a little easier for people who don't know the addon well enough yet.

**Comment by fonol** [comment]
Hi, thanks for the feedback, you are right, it could be explained further. Plus I noticed that you can create a pdf note if you only fill out the Text field, and not the Title, which doesn't really make sense. I will include these changes with the next update.
