### ISSUE TITLE
Pick up where you left off.

### ISSUE THREAD

**Issue by An-png** [fonol/anki-search-inside-add-card#108]
If you go to page 3 on a PDF, and then close the "add" dailog, then re-open the add-dialog and click "Read Next", then you will be set back to page one. Ideally what page you were reading at should be saved for every single PDF.

**Comment by fonol** [comment]
Not ideal, but atm, it opens pdfs at the last page marked as read.

**Comment by An-png** [comment]
Hey @fonol, you can close issues/feature requests after you have fixed/implemented them 😅

**Comment by An-png** [comment]
Also, the changelog in the actual add-on is completely different to the one on the Ankiweb page. The changelog in the add-on mentions changes that are not present in the ankiweb page changelog.

**Comment by fonol** [comment]
> Hey @fonol, you can close issues/feature requests after you have fixed/implemented them 😅

Did not remember that there was a github issue for this ;-)
The changelog is not different, it just stopped at some point. I am now only listing the changes in the add-on itself, I guess in general that's more convenient.

**Comment by An-png** [comment]
> The changelog is not different, it just stopped at some point. I am now only listing the changes in the add-on itself, I guess in general that's more convenient.

Problem with this is that old changelogs could get lost...
Are the old changelogs being stored anywhere? Because it's not in the github releases.

**Comment by fonol** [comment]
If you really feel you need the older changelogs, you can always use the git history https://github.com/fonol/anki-search-inside-add-card/commits/master/src/web/web.py

**Comment by An-png** [comment]
thanks
