### ISSUE TITLE
Comparison button not appearing anymore

### ISSUE THREAD

**Issue by succil** [fonol/anki-search-inside-add-card#116]
This button is missing after last update.

I'm in 2.1.26 version

Before:

![image](https://user-images.githubusercontent.com/63019606/85187085-59745200-b273-11ea-98bc-4917a01746d5.png)

After:
![image](https://user-images.githubusercontent.com/63019606/85187128-c4be2400-b273-11ea-97aa-cbc57194204f.png)

**Comment by fonol** [comment]
Hi, I removed it intentionally (I also wrote it in the changelog, I called it "float" button). Did you have any use for it? I never used it, and it didn't really look good anymore either, so I figured I might use the space for some other button in the future.

**Comment by succil** [comment]
Yes I do . I use your add-on a lot to search and compare info. I put like three or more notes to create a context/link between them. So, viewing my cards side by side is very useful to me because my information is somehow relatable but not that much. As a law student, sometimes "The devil is in the detail" and we only notice when comparing them. That's why porter stemming, fuzzy search, autocompletion, narrowing results and zettelkasten method are so important to me. I know nothing is perfect, but having this float button (I didnt know its name) is a handy tool.

**Comment by succil** [comment]
Yes I do . I use your add-on a lot to search and compare info. I put (or click on float button) like  on three or more notes to create a context/link between them. So, viewing my cards side by side is very useful to me because my information is somehow relatable but not that much. As a law student, sometimes "The devil is in the detail" and we only notice when comparing them. That's why I miss those tools in Anki like a Webcliper (like evernote has consulting user's database when searching terms through google), pop up dictionary while reviewing (context search as a side panel), porter stemming, fuzzy search, autocompletion, narrowing results, zettelkasten and other methods (as I mentioned in #84  - Search box, keywords and relatable terms) are so important to me. I know nothing is perfect, but having this float button now (I didnt know its name) is a handy tool. Wish I could have any spare time to learn python and implement those functions as a PR but I know, it isn't an easy task to begginers.

**Comment by fonol** [comment]
I added it again as a config option. It will be included in the next update.
