### ISSUE TITLE
Copy card id button on the card in search window itself

### ISSUE THREAD

**Issue by ComstockGordon** [fonol/anki-search-inside-add-card#117]
I use this addon with "link cards/notes" addon. A button to copy card id on the info window is great. But it would be even better if a button to copy card id was right there on the search screen as in the photo below. 

![Screenshot 2020-06-22 at 1 52 38 AM](https://user-images.githubusercontent.com/67241802/85234496-650a7900-b42b-11ea-9241-9cd620e59cdf.png)

Thanks for all your efforts. This is probably the best Anki addon.

**Comment by fonol** [comment]
Included in the last update.

**Comment by ComstockGordon** [comment]
Hi, thanks for including it in the latest update. However, the addon uses card ID instead of note ID to open linked cards in previewer. Can you please include an option to copy the card id instead of the note id? Thanks.

**Comment by fonol** [comment]
Hm, and what about notes with multiple cards? Should it then copy the IDs of all of them?

**Comment by ComstockGordon** [comment]
I think it will work if it copies any of the card IDs, because a link can be established by referring to any card from the note.

**Comment by fonol** [comment]
Included in new version.

**Comment by ComstockGordon** [comment]
Thanks a ton! This addon gets better and better.
