### ISSUE TITLE
Not able to open PDFs after latest update

### ISSUE THREAD

**Issue by ComstockGordon** [fonol/anki-search-inside-add-card#118]
I am getting this error "Could not load PDF - seems to be invalid" every time I open a PDF. I tried editing the note and reselecting the PDF but it did not help.

I am on Anki Version 2.1.26 and macOS Catalina 10.15.4.

**Comment by ComstockGordon** [comment]
I retried after disabling all other addons. The problem still persists.

**Comment by fonol** [comment]
That's weird. I tested on Anki 2.1.24 on Ubuntu and on my Windows machine (2.1.28) and it works on both. 
It would help me immensely if you could post the javascript error that occurs. If you want to  do that, you'd have to install the "Webinspector" add-on, then try to open a PDF, right click somewhere in the dialog, click Inspect, then click on the Console tab.

**Comment by ComstockGordon** [comment]
I am clicking the inspect button as shown in the screenshot but nothing is happening. I don't know if I am doing something wrong.

![image](https://user-images.githubusercontent.com/67241802/85453054-18ed3f00-b5b9-11ea-80c4-08538079c603.png)

**Comment by fonol** [comment]
Sorry, I should have mentioned, the inspector pops up on the main window.

**Comment by ComstockGordon** [comment]
Please excuse my stupidity. Here it is:

![image](https://user-images.githubusercontent.com/67241802/85454288-64541d00-b5ba-11ea-8bf0-c56232860a69.png)

**Comment by fonol** [comment]
Does it show you the line where the error occurs if you click on it?
(Sometimes you have to click, then switch the tab or close the inspector and then do it again for it to show the correct line)

**Comment by ComstockGordon** [comment]
I am not sure how to check for line numbers. I just realised there are lot of toggles under the "t.UnknownErrorException" line. Should I paste all that information here.

Also, please tell me if I can perform any other check to make sure its a bug and not an issue on my end. Thanks.

**Comment by fonol** [comment]
I don't really know if it's an issue on your end, but I don't think so.
You can click on the _data:text/..._ message. Ideally, it should highlight the location of the error in the html.

**Comment by ComstockGordon** [comment]
This is what it shows me when I click on "data:text/". I'll paste the other details here too.

![image](https://user-images.githubusercontent.com/67241802/85463564-68853800-b5c4-11ea-8181-81ac366eaee9.png)

**Comment by fonol** [comment]
Yea that happens to me too on the first time, you can try clicking on the other tab on the left side (data:text/html...) or close the html tab and repeat.

**Comment by ComstockGordon** [comment]
If I switch tabs and come back to it again, this is what it shows me.

![image](https://user-images.githubusercontent.com/67241802/85465360-55736780-b5c6-11ea-93c7-6d9219ff0d7b.png)

And yes I have tried opening other old PDFs. I also tried creating a new note with a new PDF. None of them are opening.

**Comment by fonol** [comment]
Hm, and what does appear if you uncollapse the error? 
I am wondering if the error is related to the update in the pdf.js version this add-on uses.

**Comment by ComstockGordon** [comment]
It has a lot of toggles. I am not sure how to copy it and how deep should I go. Do you need all of it?

**Comment by fonol** [comment]
No, just some levels. You could do a screenshot

**Comment by ComstockGordon** [comment]
![image](https://user-images.githubusercontent.com/67241802/85468032-8bfeb180-b5c9-11ea-8558-85555b06ca4b.png)

Please let me know if you need more information. Its getting very late here, ill post it tomorrow. Again, thanks for all your efforts.

**Comment by fonol** [comment]
That confirms it's the pdf.js update. I reverted to a slightly older version. If that doesn't fix the issue, please tell me!

**Comment by ComstockGordon** [comment]
Yes it seems to be fixed. I am able to open all PDFs. Thanks a lot!
