### ISSUE TITLE
numberOfResults

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#12]
This variable is not respected when the search is done by this field:

**Correct**
![image](https://user-images.githubusercontent.com/42243532/54219176-bf4d2800-44cd-11e9-9e56-6fe0390399da.png)

**Not Correct**
![image](https://user-images.githubusercontent.com/42243532/54219226-db50c980-44cd-11e9-8f79-378fffa200b9.png)

**Comment by fonol** [comment]
True, that is a bug. But much more important, something has to be done about how these tags look.

**Comment by cjdduarte** [comment]
I use hierarchy in the tags.

![image](https://user-images.githubusercontent.com/42243532/54226792-4786f980-44dd-11e9-9b4e-05b21e42d05b.png)


Maybe it should also implement collapse here.

![image](https://user-images.githubusercontent.com/42243532/54226855-6c7b6c80-44dd-11e9-88cd-95b4807aae5b.png)

**Comment by fonol** [comment]
I agree, but the space is just too small to show nested tags without an ugly horizontal scrollbar.
I'm gonna try to display children of nested tags in a little popup on demand.

**Comment by fonol** [comment]
new version is up :)

**Comment by cjdduarte** [comment]
Working
