### ISSUE TITLE
Image occlusion the whole page?

### ISSUE THREAD

**Issue by wiIIheIIm** [fonol/anki-search-inside-add-card#121]
First, thank you for this awesome add-on it's life changing.

Now I would like to know if there's a workaround or an option I'm not aware of in order to cut/crop/capture the whole page without having to change its ratio/zoom it.

Since I work on a small screen resolution and I sometimes need to crop/cut the whole page for getting big picture or context which require me to unzoom it to the point it's not readable once I'm reviewing it.

So I'm looking for a way to either get the whole page or making the cut/crop following the cursor when scrolling.

Thanks in advance.

**Comment by fonol** [comment]
Hi, scrolling while cropping is hard/more work, but snapshotting the whole page is probably very easy. I'll add it on my list for the next update.

**Comment by wiIIheIIm** [comment]
I just noticed you added it in the last version!
Thank you a lot for this great feature! 

Have a nice day :)
