### ISSUE TITLE
[BUG] The add on does not work with Arabic language (rtl)

### ISSUE THREAD

**Issue by gotoayman** [fonol/anki-search-inside-add-card#123]
unfortunately the add on cannot perform search in Arabic written cards , which is a right to left language, while it works smoothly with my english cards.
Anki 2.1.26
windows 10 build 2004

**Comment by fonol** [comment]
Hi, that is not really a bug, rather a missing feature ;-).
That it cannot search for arabic is not because of the RTL, but because of the arabic characters, which are not recognized at the moment when indexing and/or searching. I will look into it when I got some time, but no promises.

**Comment by gotoayman** [comment]
thank you a lot

**Comment by fonol** [comment]
The new version has some support, I am not sure how good the results are, but at least, you can search for the characters now.

**Comment by gotoayman** [comment]
the previous version wasn't giving any result fro the search, the new one gives so many irrelevant results. it seems (as shown in the attached image) that it searches for every character in the word instead of searching for the whole word. 
![2020-07-13 132819](https://user-images.githubusercontent.com/34642444/87295199-854ec480-c50d-11ea-99a9-1dd9f56eb833.jpg)

**Comment by fonol** [comment]
Okay, another try, new version is up.

**Comment by gotoayman** [comment]
Great.
Thank you a lot. It's fully working now.
