### ISSUE TITLE
Sort search based on which cards contain the most words that match the identified text in the field when searching.

### ISSUE THREAD

**Issue by yuytuyt** [fonol/anki-search-inside-add-card#124]
Your add on is amazing, just a thought from me to enhance it.

**Comment by fonol** [comment]
Hi, so basically you mean, wenn you either 
1. select text in a field (with Search on Select enabled) 
2. write in a field (with Search on Typing enabled)
it should only display results that are relevant to that one field?

**Comment by yuytuyt** [comment]
No I'll give an example: let's say the programme identifies 6 words from the text. In the search, the cards with all six words would appear first, then the ones with only 5 of the words and then 4 of them and so on in that order. Then it would show cards that are most similar to the card you made at the top and the least similar far down the list.

What you said may be useful too.

**Comment by fonol** [comment]
What you described is already what is supposed to happen.
The internal search engine ranks the cards based on the number of matches, but also on the rareness of them. E.g. if your field contains a word which you only used in one other card in your collection, it will probably be ranked very high, even above notes that may contain more matching words.

The ranking works better on newer SQLite FTS versions, maybe you have an older one? You can see the version in the `Info` dialog.

**Comment by yuytuyt** [comment]
Yeah makes sense, I updated thanks.
