### ISSUE TITLE
Bug when adding PDF.

### ISSUE THREAD

**Issue by NameLessGO** [fonol/anki-search-inside-add-card#128]
Idk how bug reports works, so i will post the debug info like the others, although it can be irrelevant, my PDF files are higher than **1.5KB-2KB** average for School textbook for the exam(ENEM/Vestibulares) maybe the language that it is in **PT-BR** might have bugged out, much "stop words"

I use with addons?(Anking 40+), but it didn't work but i also use **without all the addons** and didn't work either

Also irrelevant, is there any tutorial that explain in depth the addon, that is a extensive and impressive addon, only know how to add the pdf... or   ##not

Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-08-31 19:00:28

Caught exception:
Traceback (most recent call last):
  File "C:\Users\vidal_z2a9uvw\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\editor.py", line 196, in on_create_clicked
    success = self._create_note()
  File "C:\Users\vidal_z2a9uvw\AppData\Roaming\Anki2\addons21\1781298089\src\dialogs\editor.py", line 253, in _create_note
    create_note(title, text, source, tags, None, specific_schedule, queue_schedule)
  File "C:\Users\vidal_z2a9uvw\AppData\Roaming\Anki2\addons21\1781298089\src\notes.py", line 207, in create_note
    id      = conn.execute("""insert into notes (title, text, source, tags, nid, created, modified, reminder, lastscheduled, position, extract_start, extract_end, delay)
sqlite3.OperationalError: table notes has no column named extract_start

**Comment by fonol** [comment]
Hi, that is a really weird error. 
Have you recently installed the add-on or did you have it installed some time ago and now re-enabled it? Because the latter could explain the error. If you don't have any data to lose in the add-on yet, you could remove it completely and install it again. Then it should correctly create the database.

**Comment by NameLessGO** [comment]
It works! Thanks Fonol for the help and for the addon👏

Em ter., 1 de set. de 2020 às 01:51, fonol <notifications@github.com>
escreveu:
