### ISSUE TITLE
Error on PDF Import

### ISSUE THREAD

**Issue by wolfishbag** [fonol/anki-search-inside-add-card#129]
![Capture](https://user-images.githubusercontent.com/70773676/92273298-b49c0500-eeb0-11ea-86cb-4e819fbe0ea0.PNG)
Every time I attempt a PDF import I get this error and it doesn't allow me to  to search it. Any help would be greatly appreciated. I tried running on .22, .28. .26, and .30 versions of anki and none have worked.

**Comment by fonol** [comment]
Hi, did you by chance install the add-on at an earlier time, and then recently reactivated it?
If you don't have any data in it, simply removing the add-on and reinstalling it would fix the problem. Otherwise, you can wait for a fix that I will include in one of the next updates.
