### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#13]
I've included my list of Keywords, but some of them appear in the list below:

![image](https://user-images.githubusercontent.com/42243532/54277008-6af98500-456d-11e9-9a88-16ffb13729bb.png)

![image](https://user-images.githubusercontent.com/42243532/54276869-1eae4500-456d-11e9-8372-caabeddd15c4.png)

**Comment by fonol** [comment]
Weird... I'll have a look, thanks

**Comment by fonol** [comment]
should be fixed, new version is up

**Comment by cjdduarte** [comment]
**Perfect**

![image](https://user-images.githubusercontent.com/42243532/54280238-c0d22b00-4575-11e9-8d8d-621a06172ca8.png)


![image](https://user-images.githubusercontent.com/42243532/54280203-ad26c480-4575-11e9-9919-10e2472c74eb.png)
