### ISSUE TITLE
Searching, PDF Reading & Note-Taking in Add Dialog

### ISSUE THREAD

**Issue by Slothere** [fonol/anki-search-inside-add-card#131]
The new update crashes my Anki

![2020-09-07_17-58-01](https://user-images.githubusercontent.com/70905533/92400322-6eef6e80-f134-11ea-98f7-2488098c098f.png)
![2020-09-07_17-57-27](https://user-images.githubusercontent.com/70905533/92400325-70209b80-f134-11ea-812d-a37ee2af8f8f.png)

**Comment by fonol** [comment]
Not really sure what could be the cause. There haven't been any changes to the database code.

1. Does the problem persist if you reboot your machine? Maybe there is some process holding onto the database.
2. Have you changed the save location of the add-on's note database recently?
3. Is the `siac-notes.db` file at the location specified in the config under `addonNoteDBFolderPath` (if that value is empty, it should be in the add-on's user_files folder)?
4. Does the add-on run if you copy the `siac-notes.db` file to some other location, delete the old one, and restart Anki? It should then create an empty new database.

**Comment by Slothere** [comment]
I guess it's not where it should be?:
![2020-09-07_20-16-25](https://user-images.githubusercontent.com/70905533/92408754-22615e80-f147-11ea-894d-620e742b4b00.png)
Btw, is this siac-notes.db you're talking about, if it is I should copy it tow where exactly?
![2020-09-07_20-16-42](https://user-images.githubusercontent.com/70905533/92408757-242b2200-f147-11ea-9d9b-0efa0ce718b8.png)

**Comment by Slothere** [comment]
solved it thx

**Comment by fonol** [comment]
Mind telling what was the issue? Could be helpful in the future if people have the same error.
