### ISSUE TITLE
Everytime after an update my app crashes and when I reopen it, this error pops up

### ISSUE THREAD

**Issue by kinkeymonkey161** [fonol/anki-search-inside-add-card#137]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-26 12:57:20

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Goon\AppData\Roaming\Anki2\addons21\1781298089\src\index\indexing.py", line 238, in run
    self.t(*self.args)
  File "C:\Users\Goon\AppData\Roaming\Anki2\addons21\1781298089\src\index\indexing.py", line 104, in _build_index
    index                               = FTSIndex(corpus, index_up_to_date)
  File "C:\Users\Goon\AppData\Roaming\Anki2\addons21\1781298089\src\index\fts_index.py", line 81, in __init__
    conn = sqlite3.connect(self.dir + "search-data.db")
sqlite3.OperationalError: unable to open database file

**Comment by fonol** [comment]
Hi,
this error has been popping up a lot recently. I am working on a possible fix for one of the next updates.
In the meantime, if you cannot start the add-on, you could try opening the `user_files` folder in the add-on's folder, and delete `search-data.db` if it is there.

**Comment by kinkeymonkey161** [comment]
Hi,
Thanks for the quick reply. I checked the add-ons folders. There isn't any folder named `user_files`. I searched all the subfolders too. There isn't any.

**Comment by fonol** [comment]
it should be in the folder of this add-on (`1781298089`). If it is not there, you can create an empty `user_files` folder, and I guess it should start working again.

**Comment by kinkeymonkey161** [comment]
I created the folder and it works fine now

**Comment by fonol** [comment]
Should be fixed now with the newest update. (The error might still pop up one last time though after the update).
#138
