### ISSUE TITLE
Error message on Anki start-up since last add-on update

### ISSUE THREAD

**Issue by pineappleburger** [fonol/anki-search-inside-add-card#139]
> An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.
> When loading '⁨Searching PDF Reading  Note-Taking in Add Dialog⁩':
> ⁨Traceback (most recent call last):
>   File "aqt/addons.py", line 211, in loadAddons
>   File "/Users/Jo/Library/Application Support/Anki2/addons21/1781298089/__init__.py", line 4, in <module>
>     from . import src
>   File "/Users/Jo/Library/Application Support/Anki2/addons21/1781298089/src/__init__.py", line 516, in <module>
>     init_addon()
>   File "/Users/Jo/Library/Application Support/Anki2/addons21/1781298089/src/__init__.py", line 71, in init_addon
>     state.db_file_existed = create_db_file_if_not_exists()
>   File "/Users/Jo/Library/Application Support/Anki2/addons21/1781298089/src/notes.py", line 77, in create_db_file_if_not_exists
>     conn = sqlite3.connect(file_path)
> sqlite3.OperationalError: unable to open database file

Anki Version 2.1.34 (8af8f565)
Python 3.8.0 Qt 5.15.1 PyQt 5.15.1
MacOS Catalina Version 10.15.6

**Comment by fonol** [comment]
Hi, when exactly was your last update? The most recent update (today, ~16:20) should fix that error, maybe you don't have that one yet?

**Comment by pineappleburger** [comment]
Thanks for your fast reply! (and excuse my rather late one)

I updated it and now it works like a charm. Sorry, I thought I already had the latest update installed. -.-'
