### ISSUE TITLE
Keywords 2

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#14]
I do not know if it is a bug, but there is a word that I added in the "stopwords" 
and continued to appear: "Resposta"

![image](https://user-images.githubusercontent.com/42243532/54298617-d9ebd380-4597-11e9-81d4-0c55886ef846.png)

**Results:**
![image](https://user-images.githubusercontent.com/42243532/54298742-1cadab80-4598-11e9-9bc6-3e5944681072.png)

I investigated why only these words kept coming and I realized that it always comes with two points (punctuation)

![image](https://user-images.githubusercontent.com/42243532/54298282-37cbeb80-4597-11e9-881d-868cfdd5ef8c.png)

I did a test and I added that word with the colon (punctuation) and it worked.

![image](https://user-images.githubusercontent.com/42243532/54298917-7dd57f00-4598-11e9-9d3c-aa0f316a9df0.png)

Result:

![image](https://user-images.githubusercontent.com/42243532/54299034-c55c0b00-4598-11e9-8df0-be985e28a52c.png)

**Because I opened this issues. The first term "Resposta" should not have ignored the term "Resposta:" with the colon?**

**Comment by fonol** [comment]
Good catch, I think there is some issue with punctuation around when assembling the keywords.
I noticed above that you have a tag that has 26 subtags, when you click on it, do they fit in the dialog at all?

**Comment by fonol** [comment]
Btw. thanks a lot for all the detailed bug reports :)

**Comment by cjdduarte** [comment]
It's a pleasure to help.

This addon will save me hours of study by avoiding duplicate cards. He adapted very well in the way I studied.
I had already thought of something like that, but you, besides coding, went beyond what I had imagined.
Congratulations

About the 26 tags, they appear like this to me. Attended me.
This tag specifically I will delete it in the future.

![image](https://user-images.githubusercontent.com/42243532/54301032-e888b980-459c-11e9-9590-6d3c68d90e74.png)

**Comment by fonol** [comment]
That's ugly, I have to set a maximum height there. I hope the two scroll bars at the side only appeared because of the dialog? Because I have spend much time to get the screen to always resize in a way that there  should be never an overflow.

**Comment by cjdduarte** [comment]
Follow GIF.

![example2](https://user-images.githubusercontent.com/42243532/54301823-73b67f00-459e-11e9-85d7-b273608fd9f1.gif)

**Comment by fonol** [comment]
Oh no, I was sure I got the layout right this time. I hate these vertical bars. I guess time for more css research.

**Comment by fonol** [comment]
new version is up, with hopefully keyword and tag dialog fixed.

**Comment by cjdduarte** [comment]
Perfect.

![image](https://user-images.githubusercontent.com/42243532/54304068-2983cc80-45a3-11e9-86d5-de9efb059a45.png)
