### ISSUE TITLE
failed to toggle: cannot read property 'style' of null

### ISSUE THREAD

**Issue by galantra** [fonol/anki-search-inside-add-card#148]
I have deleted the add-on and re-downloaded it. I have also deleted siac-notes.db as suggested in #147.

The issue:

1. The add-on gui doesn't appear.
2. When I try to toggle it via Ctrl+F, I get this tooltip: `failed to toggle: cannot read property 'style' of null`

It has been like this since the last update, I think.

**Comment by fonol** [comment]
Hi, I would need some more information.

1. What Anki version do you have?
2. Does the issue persist if you disable other add-ons?

**Comment by galantra** [comment]
Sure.

1. 

> Version 2.1.22 (0ecc189a)
> Python 3.8.0 Qt 5.14.1 PyQt 5.14.1

2. I moved all other add-ons out of the folder and in fact, the issue doesn't persist. I'll try to find out which is conflicting. I recently added some new add-ons.

**Comment by galantra** [comment]
I get the error only in the edit window, not the add windows.

**Comment by fonol** [comment]
Did you find out which add-on was causing this?
