### ISSUE TITLE
"Sorry, could not extract any sentences" Error

### ISSUE THREAD

**Issue by jwestrupp2110** [fonol/anki-search-inside-add-card#158]
I really love this add-on.

But I keep getting the "Sorry, could not extract any sentences" Error when I try to select a sentence.

I have tried it with 5 textbooks, yet keep getting the same message.

I even tried to vary the selection length from very long to very short to no avail.

How would you recommend I fix this?

![image](https://user-images.githubusercontent.com/70381391/98524658-7d294a80-229d-11eb-8ade-cbef854ead3e.png)

**Comment by fonol** [comment]
Hi, thanks for the report. I would need some more information:
1. Does this problem occur with different PDFs?
2. What happens if you disable the "search on select" in the PDF viewer, select some text, copy it, and paste it somewhere? Does it come out correctly, or is it garbled?
3. In the image you posted, there does not seem to be any highlighted/selected text. How did you produce the screenshot?

**Comment by jwestrupp2110** [comment]
Thanks for the prompt response.

1. It did occur with 3 of the 5 PDFs I tried. For the other 2 PDFs, I was able to make it work most of the time, yet got the error sometimes.

2. When I disable the "search on select" in the PDF viewer and copy-paste text elsewhere, it comes out correctly.

**Comment by fonol** [comment]
Oh, do you select the whole sentence? Because that's not how its intended to work, you select only the part you want to have "clozed-out".

**Comment by jwestrupp2110** [comment]
I tried selecting only a word but got that error. However selecting an incomplete sentence seems to work. Will keep doing so

Thank You for the prompt reply and for this wonderful add-on.

**Comment by jolars** [comment]
I am getting the same error too and it occurs seemingly at random. See the animated GIF below:

![Peek 2021-08-23 10-07](https://user-images.githubusercontent.com/13087841/130413031-0cae91fe-16d9-40c1-986a-5c970b9cbc1c.gif)

**Comment by jolars** [comment]
A related issue is that, when selecting a word and generating a cloze, the surrounding sentence (context) is sometimes taken from another sentence on the same page. See below. This seems to happen for the same sentences that the issue above occurs for.

file:///home/gerd-jln/Downloads/Peek%202021-08-23%2010-13.gif
