### ISSUE TITLE
Button RANDOM

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#16]
Let's go another one. 👍 

What is the function of the RANDOM button? Is randomizing other results limited by "numberOfResults" = 100, and showing other cards initially skipped?
If so, by clicking this button, it ignores the text entered in the search field on all cards in the deck.

![example3](https://user-images.githubusercontent.com/42243532/54305270-b6c82080-45a5-11e9-9ece-292afb55422e.gif)

**Comment by fonol** [comment]
It gives you 100 (or whatever you have set your limit to) randomly selected notes, only restricted by your current deck selection. I should probably add some kind of tooltip on hover or something like that.

**Comment by fonol** [comment]
Intention was to get some random notes and maybe find some which are improvable this way,

**Comment by fonol** [comment]
I have thought about some kind of predefined search that gives you the notes in your collection on whose cards you performed the worst. So you get the notes / topics which need refinement the most

**Comment by cjdduarte** [comment]
Got it. Is that I imagined the following situation: If there was no limitation, it would return 532 cards (for example). Due to limitation, it will bring 100 cards. I figured this button could bring another 100 cards randomly from the initial 532.

**Comment by cjdduarte** [comment]
What ordering criteria? Similarity between all words?

**Comment by fonol** [comment]
order is completely random too ;)

**Comment by cjdduarte** [comment]
Why my question. Here in Brazil, we study for exams where there are up to 25 subjects, multiplied by about 10 pdfs each subject. And each pdf can have about 100 pages. In addition to studying by database of exercises that exist.

On average we get to create between 10 and 30 thousand cards in Anki to absorb all this content. This addon will help eliminate and avoid creating duplicate or similar cards.

I could have instead of 20,000, 8,000 unique cards without repetition.

In my example that I sent up, I found 8 similar cards that could be reduced to only 1 (or would not be created if the add-on existed before).

**Comment by cjdduarte** [comment]
Tanks

**Comment by fonol** [comment]
Wow, that is quite excessive. I mean, I doubt the average Anki user has more than 10-15k cards even after years. Do a lot of students in Brazil use Anki?

**Comment by cjdduarte** [comment]
> Wow, that is quite excessive. I mean, I doubt the average Anki user has more than 10-15k cards even after years. Do a lot of students in Brazil use Anki?

It is not yet widely known. But it has its considerable share and has increased. Self-performance students have excelled here with the use of Anki.

Here to enter a public university, it is necessary to take a test and only those with the highest marks (qualifying) enter. Vacancies for medicine mainly is very concurred. And some have got thanks to Anki.

**Comment by cjdduarte** [comment]
In 2018 there were 5.5 million confirmed registrants to take this test. But Anki users would risk no more than 5 thousand.

**Comment by cjdduarte** [comment]
> What ordering criteria? Similarity between all words?

Do you think anything can be done about it?

**Comment by fonol** [comment]
You mean you should get random notes from your selected decks, but the notes are ordered in a way of similarity to what? your current typed text, or should they be grouped by similarity to each other? I the latter, this would take quite some time for 100 notes, since for every single one you would have to go through all 99 others, compute similarity, etc. So essentially cubic in runtime. But I like the idea, maybe I will try to set up some predefined search "find very similar notes" or something like that.

**Comment by cjdduarte** [comment]
> But I like the idea, maybe I will try to set up some predefined search "find very similar notes" or something like that.

I think there is some library that does this (Text mining). But it is just an idea and would be very useful, but what you have done helps a lot.

I'll close this thread because it's about the BUTTON.
