### ISSUE TITLE
Can't close the search window when in fullscreen

### ISSUE THREAD

**Issue by awesome-rdash** [fonol/anki-search-inside-add-card#161]
The button to turn off the screen window disappear when I put the window in fullscreen,

![image](https://user-images.githubusercontent.com/2684614/99158403-b9f8a580-26d2-11eb-8e8a-e0f082387513.png)

Thanks,
Justin

**Comment by fonol** [comment]
Hi, that is kind of intentional. The toggle button appears when the window is small enough so that only either the fields, or the add-on pane are shown. If the window is big enough to show both, side-by-side, the button is not displayed (but you can toggle with the shortcut (CTRL+F) in both cases.

**Comment by awesome-rdash** [comment]
Hi, thanks for the answer. I wasn't aware of this shortcut. Thanks!
