### ISSUE TITLE
Text selection in cloze generation not working as expected

### ISSUE THREAD

**Issue by claford-v-lawrence** [fonol/anki-search-inside-add-card#163]
Suppose I want to generate a close from the following page
<img width="971" alt="image" src="https://user-images.githubusercontent.com/42150595/99215386-ac940600-280d-11eb-857d-4e92e0e6da46.png">
I got 
> A b ottom-up parse corresp onds to the construction of a parse tree for an input string b eginning at the lea v es (the b ottom) and w orking up to w ards the ro ot (the`

instead. Is there any way to fix this? I'm already using the alternative renderer.

**Comment by fonol** [comment]
Hi, unfortunately, that is how text comes out of pdf.js for some PDFs, and there is not much I can do about it. Internally, the characters in the PDF are just absolute positioned glyphs, and pdf.js tries to correctly assign/segment them into words. That works ok for most PDFs, but for some, the results are not that great.
https://github.com/mozilla/pdf.js/issues/12509
https://github.com/mozilla/pdf.js/issues/9998
https://github.com/mozilla/pdf.js/issues/6705

**Comment by claford-v-lawrence** [comment]
Thanks for your efforts anyway! Your project really helped me a ton:P
