### ISSUE TITLE
A suggestion regarding the UI

### ISSUE THREAD

**Issue by dummifiedme** [fonol/anki-search-inside-add-card#169]
I feel the read button sould be near the page navigation buttons (Prev and Next page buttons) so that we can check the page as read while clicking for the next page. Currently the 'read' button is far out at the right.

Just a suggestion :)

![image](https://user-images.githubusercontent.com/68785729/99896767-ac868100-2cb9-11eb-8358-aa78f2d118b0.png)

**Comment by fonol** [comment]
Visually, I prefer the button on the right. 
For marking the current page as read and proceeding to the next page, there is a shortcut, `Ctrl+Shift+Space` by default, but editable in the settings dialog ;)

**Comment by dummifiedme** [comment]
Ah, then there's no problem at all.
Thanks. My bad for not checking out the shortcuts.

:)
