### ISSUE TITLE
Trying to 'Read First in Queue' raises an error

### ISSUE THREAD

**Issue by tardiggerAde** [fonol/anki-search-inside-add-card#173]
**What I did:**
- Downloaded the addon
- Clicked SIAC -> Import -> New
- Added a random PDF, titled it "Test", pressed Ctrl + Return
- Clicked SIAC -> Read First in Queue

**Error message**
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.36 (c505894b) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-09 21:18:37
Add-ons possibly involved: ⁨Searching PDF Reading  Note-Taking in Add Dialog⁩

Caught exception:
Traceback (most recent call last):
  File "/home/adeeb/.local/share/Anki2/addons21/1781298089/src/menubar.py", line 86, in read_first
    tooltip("Queue is empty!")
NameError: name 'tooltip' is not defined
```

**Additional info that might help**
- I installed Anki from the official website, but can reproduce this problem in the version packaged in official repository (Manjaro)
- No other addons are currently enabled
- Running anki from console sends out this message: `add-on should use methods on col.decks, not col.decks.decks dict`

EDIT: I can open the pdf from the Queue Manager -> PDF notes -> Open

**Comment by fonol** [comment]
Thanks for the report, this will be fixed with the next update.

**Comment by tardiggerAde** [comment]
Installed update, instantly fixed the Read First button, improved performance on the PDF reader, and killed every mosquito in a 3 mile radius. Thank you!!

To be thorough: Launching from the console still gives me warning messages saying `add-on should use methods on col.decks, not col.decks.decks dict`, but it doesn't seem to affect anything.
