### ISSUE TITLE
Import Text Note Formatting

### ISSUE THREAD

**Issue by lanamacdo** [fonol/anki-search-inside-add-card#175]
Is there any way to preserve formatting (i.e. highlighted text) when importing a new text file?  The "Clean" dropdown has two options which I don't use -- I'd like to "not" Remove All Formatting if possible.

**Comment by fonol** [comment]
By importing you mean Copy+Paste?
Highlights will always vanish, as there is no color in markdown.
But in general, paragraphs and bold/italic text should remain.

**Comment by lanamacdo** [comment]
Thanks very much for prompt answer.  I will try using bold/italics instead of colour for the text documents I'm working from.
