### ISSUE TITLE
"Import New" window is too large for my screen

### ISSUE THREAD

**Issue by tardiggerAde** [fonol/anki-search-inside-add-card#177]
**This is how the main page of Anki is displayed:**
Notice that the whole of the window is visible above the panel
![screenie1](https://user-images.githubusercontent.com/52736843/101766558-29648800-3b0d-11eb-8801-42cb0725923e.png)

**This is how the Import New page looks immediately after I open it:**
Several part of the window get pushed down below the panel
![screenie2](https://user-images.githubusercontent.com/52736843/101766606-371a0d80-3b0d-11eb-923e-32247d5a0100.png)

**This is how it looks after I restore and maximize it:**
An improvement, but the Create button is still unreachable
![screenie3](https://user-images.githubusercontent.com/52736843/101766644-47ca8380-3b0d-11eb-86f2-f3ba309e93ea.png)

**Additional info:**
- Screen resolution: 1366x768
- KDE Plasma 5.20.4
- I am aware that the Ankiweb page has some instructions for small window sizes, but I couldn't find the Left Side Width or Zoom options anywhere. Super sorry if I am missing something obvious here.
- Not a huge issue for me since I can Ctrl + Return to Create, but thought I would bring it to your attention

**Comment by fonol** [comment]
I honestly haven't thought of that small screen sizes. I think the problem is that some elements (in case of the note editor, the tag area on the top-left, and the text input on the right) have a minimum height set, which might have to be decreased if the screen size is small. The update on Ankiweb now decreases the min height for screen sizes < 1400. Please report back if it should still be too large your screen.

**Comment by tardiggerAde** [comment]
Thanks for the quick response. Installed the update, but the behavior is unchanged from before. This is how it looks after restoring and maximizing.

![screenie4](https://user-images.githubusercontent.com/52736843/101786526-3c388600-3b28-11eb-99e0-41241387d2fa.png)

I also tried the "Hide left side by default" option under Settings without any luck.

If it's possible, could you make the size of the text input area adjustable? Or maybe add a fullscreen option to that window?

**Comment by tardiggerAde** [comment]
I have managed to find a workaround by setting a special Window Rule that forces "Raise above" for the New Note window. Another option that also worked was to force fullscreen. 

Now that's good enough for me, but if you wanna work on interface scaling in the future, I will be glad to help out with the testing :D

**Comment by fonol** [comment]
A new version is on Ankiweb, if you want to try out.

**Comment by tardiggerAde** [comment]
Aaaaand that's another bug squished into oblivion!

Final result:
![success](https://user-images.githubusercontent.com/52736843/101984791-e55cb900-3cad-11eb-9706-e3ed676ff367.png)

All buttons are also visible with the window restored. Thank you so much for putting in the work to solve this one, even after I already figured out a workaround :)
