### ISSUE TITLE
Searching Within Cyrillic Notes

### ISSUE THREAD

**Issue by lanamacdo** [fonol/anki-search-inside-add-card#186]
I use the Cyrillic alphabet for learning Mongolian.  I've found that I cannot search for these words within SIAC notes, whether in the title or the body of the note.  Is this a possible enhancement?
Thank you

**Comment by dzes483** [comment]
I would be very interested in this feature as well. I am using it for Russian and the add-on only finds the English words.

**Comment by fonol** [comment]
Hi, it will work with the next update.
