### ISSUE TITLE
Feature request: Go to Random unread page

### ISSUE THREAD

**Issue by tardiggerAde** [fonol/anki-search-inside-add-card#187]
**Proposed enhancement:**
The navigation menu next to the Read/Unread button lets you go to the First Unread as well as Last Read page. A new option called "Random Unread page" takes you to a random page which you have not yet read. The button can be clicked again to go to another random page.

**Rationale:**
This may be useful when reading through a magazine or an encyclopedia - large books in general. Right now, I can simulate this by generating a random page number and typing it in (repeats do happen but aren't a huge deal). 

Overall, this would just be a nifty thing to have! Thanks a lot for the great work on this addon, especially the color schemes.

**Comment by fonol** [comment]
Hi, I like the idea, I am quite fond of functions that pick stuff to do randomly, as you might have guessed from the many random buttons in the add-on.
I'll try to sneak it in in one of the next updates.

**Comment by tardiggerAde** [comment]
Tested the new update, and the Random Unread option works exactly as envisioned. Thank you sooooo much :)
