### ISSUE TITLE
Pdf Page Slider not seen

### ISSUE THREAD

**Issue by slckozts** [fonol/anki-search-inside-add-card#198]
Hi, thanks for great add-on and your efforts.

My problem is I cannot scroll-down pdf page and slider not seen. 
Is that a problem with my pdf wiever or anki version or something else?
Thanks for your help.

![687](https://user-images.githubusercontent.com/77302685/104350109-d8352300-5514-11eb-8942-b54e32c8efd2.png)

**Comment by fonol** [comment]
Hi, thanks for the report!
I think I remember a similar issue some time ago, where the layout didn't work on an older Anki (and thus Chromium) version.
What Anki version are you on, 2.1.22 or 2.1.23 by chance?

**Comment by slckozts** [comment]
Versiyon 2.1.35

**Comment by fonol** [comment]
Huh, that's weird.
What does it say about `Chromium Version` (Settings & Info > Info)?
Does the problem occur with every PDF, and does it occur with other add-ons disabled?

**Comment by slckozts** [comment]
i dont get it cromium version  but it's written Version 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.12.6 PyQt 5.12.3 
and yes problem occur every pdf files 
other add-ons not disabled.

**Comment by fonol** [comment]
Qt 5.12 means Chomium 69.
Did you install Anki 2.1.35 using the standard installer, or the alternate installer?
The alternate installer has a lower Qt version included, so also a lower Chromium.

**Comment by fonol** [comment]
Okay I tested it, it is definitely the Chromium version. I got all kinds of layout problems on Chromium 69.
So the solution would be to not use the alternate installer if possible.

**Comment by fonol** [comment]
I pushed an update to Ankiweb, might fix the problem.

**Comment by slckozts** [comment]
thanks
