### ISSUE TITLE
search on selection buggy on linux

### ISSUE THREAD

**Issue by fonol** [fonol/anki-search-inside-add-card#2]

**Comment by ijgnd** [comment]
I have an autosearch bug in "search on selection" on windows and linux. I used Anki 2.1.9 without other add-ons. I have just one deck: [Ultimate Geography v3.0](https://ankiweb.net/shared/info/2109889812)

- windows: https://streamable.com/ye978  (discussed last night [on reddit](https://www.reddit.com/r/Anki/comments/axpvjf/search_collection_inside_add_cards_dialog/ehyd075/). this is the video with the overflowing at the bottom
- linux: https://streamable.com/06s7f . when I enter a second term into a field the results for this are add-ed to the search results. The search results are not cleared. If I search in the browser for "france portugal" I don't get any hits. This video was made in a new profile with a unmodified basic note type. OS: Linux Mint19 .
