### ISSUE TITLE
disableNonNativeSearching and config.md

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#20]
disableNonNativeSearching. 
What does this setting do? Not in manual.

Will you create config.md file?
**Example**
![image](https://user-images.githubusercontent.com/42243532/54353826-c3935580-4633-11e9-8b81-f08ff80d18fd.png)

**Comment by fonol** [comment]
I did not know it was possible to add explanations to the config file. Nice. 
disableNonNativeSearching is intended for people where none of the searching methods work (no fts available, and whoosh doesn't work because on mac). So that people in these rare circumstances can at least use the addon for the bottom search bar. I also wrote explanations about the different config options on the addon page.

**Comment by fonol** [comment]
btw. a new version is up with a new config option, which might be relevant for you, see the addon page for details

**Comment by cjdduarte** [comment]
> I did not know it was possible to add explanations to the config file. Nice.
> disableNonNativeSearching is intended for people where none of the searching methods work (no fts available, and whoosh doesn't work because on mac). So that people in these rare circumstances can at least use the addon for the bottom search bar. I also wrote explanations about the different config options on the addon page.

Yes, this config.md is very nice

**Comment by cjdduarte** [comment]
> btw. a new version is up with a new config option, which might be relevant for you, see the addon page for details

Updated. Very good to be able to click on the keywords. That helps a lot.
But about the setup. What are you talking about?

**Comment by fonol** [comment]
I noticed in some of your screenshots that you have a vertical scrollbar in your window. This probably comes from the result area (where the notes are displayed) being too high. So I added addToResultAreaHeight in the config file. You can try out some values there to fit the addon to your screen size. -100 for example means make the result area 100px smaller.

**Comment by cjdduarte** [comment]
Wow, it was perfect.
In my case, the value -170.

I use other addons that add more information on the screen and using this value, no longer generated the scroll bar.

**Comment by cjdduarte** [comment]
@fonol 

But in my case, depending on the size of the keywords they stay in 6 lines, generating a scrollbar.

I will open a specific topic on this.
