### ISSUE TITLE
How to migrate to a new computer?

### ISSUE THREAD

**Issue by KungManKit** [fonol/anki-search-inside-add-card#202]
How to migrate all the data of this add-on, including the PDF files and the queue, to a new computer? A walkthrough on this would be appreciated!

**Comment by fonol** [comment]
Hi, 
the queue data is stored in the `siac-notes.db` file, whose location you can see under `Settings & Info` -> `Info` -> `Path to Note DB`.
I would generally do it like that:
1. Copy the add-on's folder from your old machine to Anki's add-on folder on your new machine.
2. Start Anki, check what it says on the above given location about your `siac-notes.db` file, then go to that folder, and replace the new, empty `siac-notes.db` with the one from your old pc.
3. For PDFs whose paths might be different on your machine, there is no automatic solution, I guess you'd have to manually  update their source field to have the correct path on your new PC.

**Comment by KungManKit** [comment]
> Hi,
> the queue data is stored in the `siac-notes.db` file, whose location you can see under `Settings & Info` -> `Info` -> `Path to Note DB`.
> I would generally do it like that:
> 
> 1. Copy the add-on's folder from your old machine to Anki's add-on folder on your new machine.
> 2. Start Anki, check what it says on the above given location about your `siac-notes.db` file, then go to that folder, and replace the new, empty `siac-notes.db` with the one from your old pc.
> 3. For PDFs whose paths might be different on your machine, there is no automatic solution, I guess you'd have to manually  update their source field to have the correct path on your new PC.

Thanks for the reply! Can you further elaborate on step 3 on where can I update the source field of the PDF file? Do I need to update the path of each PDF one by one? Or is there a place I can update the folder path?

**Comment by fonol** [comment]
Yea, I mean there is no way for the add-on to know where these files are located on your new computer.
If you click on `PDFs` in the add-on's sidebar, you get a card with some filtering options, there is also the option to `Find Invalid Paths`, which will present you all the notes whose `Source` field contains a path to a pdf file that couldn't be resolved on your new computer. You'd have to edit these (via the pen icon) and put the correct path to the pdf in the source field again, one by one. Hope that helps!
