### ISSUE TITLE
Error when unsuspending cards

### ISSUE THREAD

**Issue by Meddymatt** [fonol/anki-search-inside-add-card#209]
![image](https://user-images.githubusercontent.com/78697531/107154014-8d090700-693e-11eb-9200-c3a2a6a42785.png)

hopefully the error report picture i added shows up, but i continually have this issue where once i unsuspend a card and exit that cards window, an error report pops up and then the addon no longer works until i restart anki. once i restart anki the card will be unsuspended but if i try to unsuspend another card the error happens again and i have to restart

**Comment by fonol** [comment]
Thanks for the report, a fixed version should be on Ankiweb.

**Comment by Meddymatt** [comment]
> Thanks for the report, a fixed version should be on Ankiweb.

bless your soul
