### ISSUE TITLE
 Scrollbar is generated when 6 lines of keywords appear.

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#21]
Depending on the size of the keywords they stay in 6 lines, generating a scroll bar.

**5 lines (OK)**
![image](https://user-images.githubusercontent.com/42243532/54357969-05c19480-463e-11e9-9181-0e82852fe4c0.png)

**6 lines (scroll-bar)**
![image](https://user-images.githubusercontent.com/42243532/54358028-2ab60780-463e-11e9-8c93-474940dd6281.png)

**Maybe slowing that space up.**

![image](https://user-images.githubusercontent.com/42243532/54358121-5df89680-463e-11e9-913f-df0a4f09bb5f.png)

**Comment by fonol** [comment]
Good catch. I think I will reduce the spaces there a bit. Btw., does the height of the area still fit if you collapse the top bar?

**Comment by cjdduarte** [comment]
> Good catch. I think I will reduce the spaces there a bit. Btw., does the height of the area still fit if you collapse the top bar?

I did not understand the question well. After I set the addToResultAreaHeight (-170) property, everything was perfect. Related to this scroll bar, even though it appears, the rest is OK.

**Comment by fonol** [comment]
I meant if you press the ^ shaped button on the top right, but I just tested it myself :)

**Comment by cjdduarte** [comment]
Now I understand. When I click on it, the scroll bar disappears.

![example4](https://user-images.githubusercontent.com/42243532/54361100-16293d80-4645-11e9-9a27-3ef084d9fb60.gif)

**Comment by fonol** [comment]
space should be reduced now

**Comment by cjdduarte** [comment]
Perfect. Resolved.
