### ISSUE TITLE
use html format to add notes?

### ISSUE THREAD

**Issue by oqicloud** [fonol/anki-search-inside-add-card#210]
![image](https://user-images.githubusercontent.com/55317736/107447246-13119180-6b7b-11eb-8124-fd75a5e8ec3d.png)
Can I call the pictures in the collection.media folder? Images added in html format will be removed when reading.

**Comment by fonol** [comment]
Hi, you should be able to insert them in Markdown syntax, e.g.
`![](image_in_collection.media_folder.png)`. In the reader, you will only see it if you go into preview mode though.

**Comment by oqicloud** [comment]
> ![](image_in_collection.media_folder.png)

Normal display thank you
