### ISSUE TITLE
Suggestion for improvement: Link to edit the card

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#22]
I noticed with your addon that sometimes I do not need to create a new card, but could add or update information to an existing card.

There could be a shortcut (similar to the image below) where I clicked and it displays the filtered card in the panel.

![image](https://user-images.githubusercontent.com/42243532/54377592-2ef51b80-4664-11e9-9231-98a9c54dcdfc.png)

![image](https://user-images.githubusercontent.com/42243532/54377964-091c4680-4665-11e9-9670-26911376fb5a.png)

**Comment by fonol** [comment]
Yea, I don't think this would be complicated, BUT it might be a bit confusing to still see the unchanged card in the search results until the index is rebuilt. Let's see

**Comment by cjdduarte** [comment]
I understand, without this, I'll have to look for a card on the dashboard to edit it, taking time.

This functionality would simplify the work by switching between two open windows.

For me, the addon can already be considered ALPHA :-)

**Comment by fonol** [comment]
new version is up ;)

**Comment by cjdduarte** [comment]
> new version is up ;)

Whaaaaaaaaaaaaaaat?????????????????????????

THANK YOU @fonol
