### ISSUE TITLE
Cannot display Japanese character from imported PDF?

### ISSUE THREAD

**Issue by HQYang1979** [fonol/anki-search-inside-add-card#221]
Not sure why, my PDFs cannot display Japanese characters.
 
![image](https://user-images.githubusercontent.com/74698160/108736760-d144fb80-7529-11eb-828c-05a62cffed77.png)

**Comment by fonol** [comment]
HI,
I just tested with some random pdf file with japanese characters, and they work for me.
It might be a problem with pdf.js, the library used in the add-on to render the pdfs.
Does the problem occur with every japanese pdf or just with that specific one?

**Comment by HQYang1979** [comment]
Yes, all PDFs with Asian characters cannot be displayed (Chinese and Japanese). Maybe I need to install Adobe Reader?

**Comment by fonol** [comment]
> Maybe I need to install Adobe Reader?

No, that's not it.
Got any example pdf file you can share?

If you have firefox installed, do these pdfs display fine if you open them with firefox?
Also, if you start Anki from the console, got any errors printed there when you open the pdf? (if you are on Windows, you can start the console version with `anki-console.exe` in Anki's installation folder)

**Comment by HQYang1979** [comment]
No problem open it in Chrome or firefox.  Ah, there are some errors, but I don't know how to fix it.

![image](https://user-images.githubusercontent.com/74698160/108837617-64357280-75ca-11eb-8b65-caf93cbaea60.png)

**Comment by HQYang1979** [comment]
is there any fix? Great Add-on.....

**Comment by fonol** [comment]
A possible fix will be in the next update.

**Comment by HQYang1979** [comment]
Looking forward to it, man you are doing a great job!

**Comment by HQYang1979** [comment]
the bug persisted even after yesterday's update.

**Comment by fonol** [comment]
Closing, see #223
