### ISSUE TITLE
PDF comments written in Korean are not displayed.

### ISSUE THREAD

**Issue by comienzo2093** [fonol/anki-search-inside-add-card#223]
Hi,

I wrote a pdf comment(Text box) in korean by pdf experts on ipad, this is not displayed in anki addon. (Comments in English and symbols are displayed normally. And Page elements in Korean, except for comments, are visible.)

I guessed this as a font problem and I installed that font on my pc, but it didn't work.

Also, the adobe reader installed on the PC showed pdf comments in Korean normally.

Like the informer below, I capture and upload the console screen.

Thank you.

![capture](https://user-images.githubusercontent.com/52667667/108995538-989b5280-76e0-11eb-9815-4da549eccea9.JPG)

**Comment by fonol** [comment]
Hi,
does the bug persist after yesterday's update?

**Comment by comienzo2093** [comment]
Hello, I just ran it after updating. I tried adding a pdf file and the same thing happens.
![capture](https://user-images.githubusercontent.com/52667667/109119682-5decf500-7788-11eb-8dc0-4fb5b177df86.JPG)

**Comment by comienzo2093** [comment]
> Hi,
> does the bug persist after yesterday's update?

Hello, I just ran it after updating. I tried adding a pdf file and the same thing happens.

![capture](https://user-images.githubusercontent.com/52667667/109119749-7230f200-7788-11eb-88fb-86771f43013e.JPG)

**Comment by HQYang1979** [comment]
This is the same bug I've encountered in the last issue. Yesterday I've updated the add on, but it persisted.

**Comment by fonol** [comment]
Uh, I typed the address wrong, I pushed another update.

**Comment by comienzo2093** [comment]
> 어, 주소를 잘못 입력해서 또 다른 업데이트를 했어요.

Thanks for the quick update. But it doesn't seem to be completely resolved yet.

![captured](https://user-images.githubusercontent.com/52667667/109125171-17e75f80-778f-11eb-8c03-593211bafd38.JPG)

**Comment by HQYang1979** [comment]
No, the bug still persisted...

**Comment by fonol** [comment]
Okay, another update is on Ankiweb.

**Comment by HQYang1979** [comment]
God, You're the most brilliant! Another update! and it works this time.

**Comment by comienzo2093** [comment]
> Okay, another update is on Ankiweb.

Wow. In my case, the problem was completely resolved. Thank you again for your hard work and quick response. Have a nice day.

**Comment by fonol** [comment]
Happy if it works now.
