### ISSUE TITLE
Search from Editor for Anki 2.1 ❌ incompatible

### ISSUE THREAD

**Issue by OQHan** [fonol/anki-search-inside-add-card#228]
[Search from Editor for Anki 2.1](https://ankiweb.net/shared/info/227080119)

**Comment by fonol** [comment]
Hi,
given that this add-on also searches from the editor, and that the add-on you linked hasn't been updated in two years, which means it might break anyway in any future Anki version, I don't think think this is worth investing time into. But thanks for the notice, I might start listing incompatible add-ons somewhere on the add-on page.

**Comment by OQHan** [comment]
![image](https://user-images.githubusercontent.com/53936795/109267281-4410e800-7844-11eb-924c-8206d85e6d5a.png)
I mostly use it for Chinese character search, and currently it gets very, very stuck when I use it.
Can I press the shortcut key after selecting the text to search only the relevant content of the current field?
