### ISSUE TITLE
macOS The screenshot is blurry

### ISSUE THREAD

**Issue by OQHan** [fonol/anki-search-inside-add-card#229]
![image](https://user-images.githubusercontent.com/53936795/109381436-74748700-7915-11eb-8f61-f2985ad26d02.png)

**Comment by OQHan** [comment]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-02-27 11:13:50

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 34, in cmd
  File "aqt/webview.py", line 114, in _onCmd
  File "aqt/webview.py", line 518, in _onBridgeCmd
  File "aqt/editor.py", line 410, in onBridgeCmd
UnicodeEncodeError: 'ascii' codec can't encode character '\uff0e' in position 21: ordinal not in range(128)

**Comment by fonol** [comment]
Hm, I would need some more information. Is every cropped-out image blurry? 
When exactly did you get that error?

**Comment by OQHan** [comment]
![blurry](https://user-images.githubusercontent.com/53936795/109438903-fcb67180-7a66-11eb-9e28-99c734f989de.png)
Every picture is blurry, maybe because of the Retina display on macOS?
Error, probably appeared after Anki jammed because I'm not very good at it yet, I'll keep an eye on it in the future, thanks.

**Comment by OQHan** [comment]
Please tell me 😁, what is the difference between Mode:Add-on and Mode:Browser, search?
When I search, for the same field two fill-in blanks (c1, c2), the search results are displayed in the same box, sometimes in two boxes, it's a bit confusing, I want to make both in one box.
Something like:[Card browser: List only one card per note](https://ankiweb.net/shared/info/797076357)

**Comment by OQHan** [comment]
Only two items are currently displayed when I am editing the current card.
I use [Persistent Editor](https://ankiweb.net/shared/info/1686259334)

**Comment by fonol** [comment]
> Please tell me 😁, what is the difference between Mode:Add-on and Mode:Browser, search?
> When I search, for the same field two fill-in blanks (c1, c2), the search results are displayed in the same box, sometimes in two boxes, it's a bit confusing, I want to make both in one box.

"Add-on" means the search is performed using the add-on's search index, which gives more relevant results in some cases. Browser means the search input is working like the search input in the "Browse" window of Anki, e.g. you can use all the special searches the browser allows for.

> When I search, for the same field two fill-in blanks (c1, c2), the search results are displayed in the same box, sometimes in two boxes, it's a bit confusing, I want to make both in one box.

Sorry can't follow, what do you mean by "boxes"? If you mean the card-like container each search result is presented in, these always contain exactly one note with all its fields.

**Comment by fonol** [comment]
> Only two items are currently displayed when I am editing the current card.
> I use Persistent Editor

Again not sure what you mean, but I also remember that this add-on and Persistent editor were not really compatible when I tested some time ago.

**Comment by OQHan** [comment]
> > 当我编辑当前卡时，当前仅显示两个项目。
> > 我使用永久编辑器
> 
> 再次不确定您的意思，但我还记得当我在一段时间前进行测试时，此插件和Persistent编辑器并不真正兼容。

This is what I call a box：[image](https://user-images.githubusercontent.com/53936795/110103168-9a4fcf00-7de0-11eb-9100-d5476dbe5907.png)

- II understand, thanks for the explanation, and have now adjusted the card making rules.
- Persistent plugin I tried to use and there is no incompatibility, but I just made the fields too complicated during use due to personal factors.
- Can you fix the problem that the screenshots are a bit blurry in macOS?
