### ISSUE TITLE
Save preferences

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#23]
It would be helpful if my preferences were saved when I left the screen.

![example](https://user-images.githubusercontent.com/42243532/54426440-a2476d80-46f6-11e9-9853-47065a408290.gif)

![image](https://user-images.githubusercontent.com/42243532/54426571-f81c1580-46f6-11e9-8fab-7c408044de45.png)

**Comment by fonol** [comment]
true. I might do it only in the session (until you close Anki) for starters, because that means no saving to disk necessary.

**Comment by cjdduarte** [comment]
It would be very useful.

**Comment by fonol** [comment]
If you close the add dialog, it should remember your choices now.

**Comment by fonol** [comment]
shit, forgot collapse button

**Comment by cjdduarte** [comment]
ok

**Comment by fonol** [comment]
took a while, but it should work now :)
