### ISSUE TITLE
Error searching text

### ISSUE THREAD

**Issue by Meddymatt** [fonol/anki-search-inside-add-card#232]
Whenever i copy over text from a PDF to the search bar, it does not support when the text has used the "-", particularly when used for words that carry over from one line to another, and instead places a little blank box in the text, like when you get a text with emojis that you dont have. this issue is new as of today and have previously had no problem using the same PDF. But now when one of those boxes shows up in place of a "-" is prevents the add-on from searching anything until i remove each one

**Comment by fonol** [comment]
Hi, thanks for the report.

> Whenever i copy over text from a PDF to the search bar

With search bar, do you mean the search bar to search in PDFs on the bottom left of the reader?

if you say the issue is new, did you start a new PDF recently. If so, could you check if the problem is across all your PDFs or just that one?
