### ISSUE TITLE
After the plug-in is updated, the screenshot function cannot be used to fill in the field of the card

### ISSUE THREAD

**Issue by WangChen-coding** [fonol/anki-search-inside-add-card#235]
**Describe the bug**
After the plug-in is updated, the screenshot function cannot be used to fill in the field of the card
**To Reproduce**
After the screenshot is filled in the specified field of the card, the content will not be displayed. After switching the card type, the contents of the screenshot will appear in the fields of other cards.
![image](https://user-images.githubusercontent.com/35593546/110598449-b8d91000-81bc-11eb-9e71-f87686fa917b.png)

![image](https://user-images.githubusercontent.com/35593546/110598352-9c3cd800-81bc-11eb-907b-350fc3b716f6.png)
After restarting the add card page, the problem can be solved, and it will appear again later

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Anki version (Help > About)2.1.40

**Comment by fonol** [comment]
Can you start Anki in console mode and look for any errors that appear if you use the scissor tool?

**Comment by WangChen-coding** [comment]
I don't know how to turn on console mode. I don't know if you will encounter this problem, but if it can't be used, I can directly use the screenshot of the system, and then paste it into the field of the card (it doesn't affect me much, but there is no such problem before the update).

**Comment by fonol** [comment]
> I don't know how to turn on console mode.

If you are on Windows, there should be `anki-console.exe` in Anki's installation folder.
I think on a Mac you should be able to start Anki with `anki` in the terminal, as on linux.

> Also, does the issue persist with other add-ons disabled?

Did you test that?

**Comment by WangChen-coding** [comment]
After all add ins are disabled, the fields that can be added to the card can be used normally. After switching the card type (including selecting the current type again), the console will report an error in the last line. At this moment, the screenshot cannot be added to the field correctly
![image](https://user-images.githubusercontent.com/35593546/111017424-641cdb80-83ee-11eb-9f90-60f36ee7b92e.png)
（normal）
![image](https://user-images.githubusercontent.com/35593546/111017350-f40e5580-83ed-11eb-8b7c-48b209d57c61.png)
（Error occurred after switching card type）

**Comment by fonol** [comment]
Thanks, I think I now know what the problem is. I'll include a fix with the next update.

**Comment by WangChen-coding** [comment]
excellent! The problem was solved after the update, and the new icon was particularly beautiful
