### ISSUE TITLE
search-data.db

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#24]
Just informative. I do not know if I have to do anything about it. You decide.
I was testing your addon on a deck of mine of 40,000 cards.

But I started using it effectively in an empty deck in another profile.
As I copied the add-on folder from the old profile, search-data.db contained the old data.

I am using it normally and it works (I opened and closed the Anki, several times), however I realized that search-data.db had 40Mb.

Delete the file (later I tested with the Vacuum command in SQLite) and the file decreased to 24kb.

I think it's trash from the previous profile.
Do you think that action is necessary?

**GIF animate:**

![example](https://user-images.githubusercontent.com/42243532/54428230-90b49480-46fb-11e9-8363-2515f5e2780b.gif)

**Comment by fonol** [comment]
Everytime the _fts_ index is built (e.g. everytime you start Anki atm), the index table inside search-data.db should be cleared.  And you don't have to copy the db file, it is created if not present. So you essentially after you copied it and switched to the other profile, it should have overwritten the 40mb index with the 24kb one. Is that what happened?

**Comment by cjdduarte** [comment]
No. It was the same size. I inserted new cards and deleted them all after. It was the same size.
It only declined when I deleted the file and it generated a new file.

**Comment by fonol** [comment]
Hm, okay, then maybe some hidden virtual tables from the index don't get deleted. So I should better always delete the .db file before rebuild just to make sure.

**Comment by cjdduarte** [comment]
Fantastic
