### ISSUE TITLE
The Content of the Card is Covered by the Source Message

### ISSUE THREAD

**Issue by lb19940508** [fonol/anki-search-inside-add-card#244]
**When reviewing the card, the content of the back of the card is covered by the _Source Message_**

- When using a `cloze` card type, after the `Extra` portion of the card is showed, I found that the content of the `Extra` field is covered by the `Source Message` pop-up box as showed in the following screenshot. 

- The pop-up box couldn't be moved around, so it kind of affected the review of the cards.
 
![image](https://user-images.githubusercontent.com/34482511/111616249-a2663080-881c-11eb-9a14-c578080e78b7.png)

**Could you please show me where can I cancel the pop-up box of the `Source Message` temporarily, or revamp it to make it movable as we scrolling down the card**
- 1. I would be really appreciated if you could show me where I could turn off the pop-up box temporarily.
- 2. Or would you please make it keep its position at the bottom of the card as we scrolling down the card, so that we could see the Extra info underneath the pop-up box.

Thanks a lot!

Best Regards.

Leo

**Comment by fonol** [comment]
Hi, thanks for the report.
Hadn't really thought about the message hiding content on the card, I have to admit.
I'll add a close button and try to make it sticky to the page, so that you can scroll the page without the message moving. Update should be out today or tomorrow

**Comment by lb19940508** [comment]
Thank you very much.
Best Regards.
Leo
