### ISSUE TITLE
Layout Issue - YouTube videos play in a very small space

### ISSUE THREAD

**Issue by anuragambasth** [fonol/anki-search-inside-add-card#252]
Hi, I have just started using your wonderful add-on, but I am facing some layout issues. When I try to play a YouTube video from the Add-on dialog, it opens up the video in a very small window. Is there a way to fix this issue? (Please see the attached screenshot). 

![image](https://user-images.githubusercontent.com/64656022/113183818-13243880-9272-11eb-8dfe-c231c2cc6440.png)

 - OS: WIndows 10. 32-bit OS. 
 - Anki version: 2.1.35 (84dcaa86)
 
 P.S. I cannot upgrade to a newer version of Anki because 2.1.35 is the last release that supports 32-bit Windows (as you might be aware).

**Comment by fonol** [comment]
Hi,
it could be a browser issue. I think the 32 bit version uses an older version of the Qt toolkit, and so also an older version of the Chromium engine. I noticed some of the layouts not behaving as intended on these older Chromium versions already some time ago. When I got some time, I might test if I can work it out, but can't really promise. PDF reader and text editor are layouted correctly?

**Comment by anuragambasth** [comment]
Hi, thanks for taking out the time to reply. 

The PDF reader doesn't work perfectly, but it is at least manageable. The full-screen button does not work, for instance. I have attached a screenshot of the PDF reader. Does it look the way it is supposed to be?

![image](https://user-images.githubusercontent.com/64656022/113188824-2803ca80-9278-11eb-8140-6ee45e18e800.png)

**Comment by fonol** [comment]
> The PDF reader doesn't work perfectly

I just tested on 2.1.35 alternate, and I noticed the whole webview feels a bit sluggish. Is that what you mean? Otherwise, please report anything you think could be an error!

The layout issue will be fixed with the next update.

**Comment by andrewcrook** [comment]
@anuragambasth  

Does this happen all the time?
Does resizing the window fix it?

I sometimes have a similar issue on Mac when I log back in after standby. 
I Presumed it was a QT issue. Resizing causes the screen to redraw properly for me.

**Comment by anuragambasth** [comment]
> @anuragambasth
> 
> Does this happen all the time?

@andrewcrook 

Yeah, it was happening every time, but I just received a new update and the issue has been fixed, thanks to @fonol. 🙂

**Comment by anuragambasth** [comment]
> > The PDF reader doesn't work perfectly
> 
> I just tested on 2.1.35 alternate, and I noticed the whole webview feels a bit sluggish. Is that what you mean? Otherwise, please report anything you think could be an error!
> 
> The layout issue will be fixed with the next update.

@fonol I just received the new update and the video player layout is working fine now. 

Regarding the PDF reader, one bug that I have noticed is that the FULL-SCREEN button does not work. Clicking on it just hides the formatting toolbar of Anki (image attached).

 
![image](https://user-images.githubusercontent.com/64656022/113448206-042bba80-9419-11eb-9f58-9e4b9c728d62.png)

P.S. Again, thanks a lot for fixing the video issue. 🙂

**Comment by andrewcrook** [comment]
Ah okay

By the way it's better to open a new ticket for each bug.
It's just easier to manage issues.

**Comment by fonol** [comment]
Yea that "fullscreen" icon is kind of a remainder from the very beginning of development. Actually, I can't really display the PDF in fullscreen easily, because the webview part of the Add window just goes from the toolbar to the beginning of the tag bar, everything else is Qt. So in HTML, I can only easily hide the fields and the button toolbar for a "fullscreen" mode. Long story short, that button does very little at the moment and I would rather tend to remove it at some point in the future.

**Comment by anuragambasth** [comment]
> Yea that "fullscreen" icon is kind of a remainder from the very beginning of development. Actually, I can't really display the PDF in fullscreen easily, because the webview part of the Add window just goes from the toolbar to the beginning of the tag bar, everything else is Qt. So in HTML, I can only easily hide the fields and the button toolbar for a "fullscreen" mode. Long story short, that button does very little at the moment and I would rather tend to remove it at some point in the future.

Oh, okay.

**Comment by anuragambasth** [comment]
> By the way it's better to open a new ticket for each bug.
> It's just easier to manage issues.

@andrewcrook Alright. I didn't know if the fullscreen button was working as intended or not. And as @fonol already commented that the button would be removed eventually, so I didn't open a new ticket. 

If I find any other bug, I would open a new issue. 

I think I should close this ticket now because the video playback layout issue has been fixed.
