### ISSUE TITLE
Feature help/request: Clickable links while reading a PDF?

### ISSUE THREAD

**Issue by Hasrp123** [fonol/anki-search-inside-add-card#263]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/82972060/115606682-b0601300-a2ec-11eb-8b8a-7ccc9bdecc64.png"> Hi all, I may be totally missing something here. But is there are way to be able to click on a link while reading a pdf? For example, in the PDF I am reading above, is there a way I can select and click on the link for the word "here" and go to that directed spot? I have PDF links enabled but I'm not able to figure out how to click on the link. I am able to do this when I use an external PDF reader like preview when reading this specific PDF. Any help would be greatly appreciated.

**Comment by fonol** [comment]
Hi, sorry for the late answer. PDF links are not recognized atm, sorry.

**Comment by Hasrp123** [comment]
Thank you for the response!
