### ISSUE TITLE
The size of the input field will automatically decrease every time a new card is added, and I have to re-save it in the field each time to restore the original default input field size

### ISSUE THREAD

**Issue by unkshl** [fonol/anki-search-inside-add-card#268]
https://user-images.githubusercontent.com/84123033/118125998-521edf80-b415-11eb-8cc2-608a58dddeea.mp4

**Comment by fonol** [comment]
Hi, 
in your video, the issue happens in the edit window, does it happen in the Add dialogue too?
What Anki version are you on?
Does it occur with other add-ons disabled?

**Comment by unkshl** [comment]
Yeah it happens in add dialogue too
anki: 2.1.43(Ofbae6bc)
Windows 10

Yeah I have tried by disabling every add on except the current one, still problem persists

**Comment by fonol** [comment]
I think I got a fix, don't really understand the source of the problem though. 
Anyway, might push an update later today.

**Comment by unkshl** [comment]
Yeah thnks for the update.
