### ISSUE TITLE
Add-On Not Compatible with Anki 2.1.44

### ISSUE THREAD

**Issue by Hasrp123** [fonol/anki-search-inside-add-card#271]
Hello I am unable to use this addon since the anki update from 2.1.43 to 2.1.44. See screenshot below. Thanks!!

[image](https://user-images.githubusercontent.com/82972060/119200025-22e22100-ba5a-11eb-9bc6-aed3de274f9a.png)

**Comment by fonol** [comment]
Hi,
Anki 2.1.44 and especially 2.1.45 did introduce a lot of changes which broke the add-on at many places. I will update it slowly to make it work again, but this might take some time.

**Comment by Hasrp123** [comment]
Thank you for the follow up. I just wanted to make you aware. This is the most valuable Anki Addon! The community and I appreciate the work you have put into this addon!
