### ISSUE TITLE
No longer provides dialogue box to generate cloze cards on selecting text

### ISSUE THREAD

**Issue by swjik76** [fonol/anki-search-inside-add-card#279]
**Describe the bug**
The dialogue box for generating cloze cards, no longer shows up when text is selected.

**To Reproduce**
1. Go to 'PDFs' within the add-on 
2. Open any PDF
3. Double click on word you wish to generate a cloze card from

**Expected behavior**
A dialogue box allowing us to quickly generate cards.

**Screenshots**
![Hnet-image](https://user-images.githubusercontent.com/79566012/123427333-1feec900-d5e2-11eb-83e6-057239dba00c.gif)

**Environment (please complete the following information):**
 - OS: Windows
 - Anki version 2.1.44

**Comment by fonol** [comment]
Hi, you have to enable the feature with the magnifying glass button (bottom left in your screenshot).

**Comment by swjik76** [comment]
Thank you for the help, really!
