### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by GrimPixel** [fonol/anki-search-inside-add-card#290]
**Describe the bug**
It took around 1GB of memory.

**To Reproduce**
Just enable it in Anki, the memory use can be observed in System Monitor.

**Expected behavior**
Take normal memory.

**Screenshots**
![addon off](https://user-images.githubusercontent.com/39795763/131985914-2bbae3fc-7da7-4603-8fe7-06901683d429.png)
![addon on](https://user-images.githubusercontent.com/39795763/131985920-62ac8e48-b6e0-4e13-aba7-e881096c752a.png)

**Environment (please complete the following information):**
 - Debian 10
 - Anki 2.1.44

**Comment by fonol** [comment]
Hi, are you sure it is the add-on causing the issue? I cannot replicate it unfortunately.
There have been problems with Qt eating memory in the past:
https://forums.ankiweb.net/t/anki-causing-high-ram-usage-v2-1-41/8132/10
https://forums.ankiweb.net/t/ram-usage-goes-up-with-each-review-leading-to-slowdown/5943
https://www.reddit.com/r/Anki/comments/ppj3sc/ram_management_issue/

**Comment by GrimPixel** [comment]
Hi, it happens only when the add-on is enabled.

**Comment by OcileCollection** [comment]
@GrimPixel Have you tried the new update? Did it solve the issue?

**Comment by GrimPixel** [comment]
Hi. It is not taking up that much memory now.
