### ISSUE TITLE
Pre-Populated Tags From The PDF Reader Are Not Getting Added to Cards

### ISSUE THREAD

**Issue by anuragambasth** [fonol/anki-search-inside-add-card#292]
**Describe the bug**
So, when I add a new PDF (using New Note), I select/choose some tags to be associated with the cards that I make from that PDF. Now, when I open the PDF reader using the ADD dialog, the TAGS field is indeed pre-populated with those tags that I had selected.

But when I add a card, those tags don't automatically get linked to that card **_unless_** I click on the TAGS field once. So, it seems like the ADD dialog doesn't realize that some tags are already there in the TAGS field unless I click on it once before adding new cards.

Also, once I click on the TAGS field, then all the subsequent cards that make from that PDF do get linked with the relevant tags.

**Expected behavior**
Tags should automatically get associated with the cards that I am adding without me having to click on the TAGS field whenever I open a new PDF.

**Environment (please complete the following information):**
 - OS: Windows 10. Version 21H1. OS build: 19043.1202
 - Anki version: ⁨2.1.47 (dc156f34)⁩

**Comment by fonol** [comment]
Thanks for the report, a fix will come with the next update.
