### ISSUE TITLE
remember state of show - hide

### ISSUE THREAD

**Issue by omega3** [fonol/anki-search-inside-add-card#30]
I start new issue because I can't reopen the last one. 

Sorry to bother you again, but consider this:
would it be possible for this add-on (hide / show) to somehow save its window state? 

Check this:
Click on Add card. Add card window opens with this add-on visible, press Ctrl+F, it hides. Click again Add card to open another Add window. Add-on part will be visible.

The same in edit: edit card, press Ctrl+F to hide, close window, go to next card in review, press edit and add-on part will be visible.

Would it be possible for this add-on to remember its state, so that it stays hidden until I press Ctrl+F again, at least until Anki cloze.

The add-on that I linked to:
Browser Maximize/Hide Table/Editor
https://ankiweb.net/shared/info/1819291495
remembers its state (even after Anki restart).

That would be very convenient.

**Comment by fonol** [comment]
Absolutely possible, and it should really work that way. I will probably include that in the next update.

**Comment by omega3** [comment]
It works. 
Thank you very much.
