### ISSUE TITLE
Button missing 

### ISSUE THREAD

**Issue by ankidoc** [fonol/anki-search-inside-add-card#301]
![CleanShot 2021-11-11 at 18 02 54](https://user-images.githubusercontent.com/81517565/141339461-972509b7-7f03-4c73-8f30-6cc3804b0829.png)
![CleanShot 2021-11-11 at 18 04 19](https://user-images.githubusercontent.com/81517565/141339474-9d8f06b1-bf3a-42f5-a830-b57cd555b7b8.png)

Hey guys! Just installed that add on and this button won't show up. I couldn't find anything in the config. Any idea?

Greetings!

**Comment by fonol** [comment]
Hi, 
what Anki version do you use?

**Comment by ankidoc** [comment]
2.1.45!

**Comment by fonol** [comment]
Should be fixed with the new version for Anki 2.1.50 (currently in Beta)
