### ISSUE TITLE
Addon UI ruins after first (successful) call

### ISSUE THREAD

**Issue by camerooncameroon** [fonol/anki-search-inside-add-card#302]
**Describe the bug**
After installing, the first try to use the addon is ok (pls see the screenshot):
![2021-11-18_17-55-23](https://user-images.githubusercontent.com/78047188/142842019-7ced1f06-ae2d-461b-81df-57666f8e3602.jpg)

... but then you try to use it for the second etc time, then it looks like:
![2021-11-18_17-55-46](https://user-images.githubusercontent.com/78047188/142842082-bd5d15ed-6313-4774-bdb7-fb903bbaa58a.jpg)

**To Reproduce**
1. Go to 'Add new Note' dialog
2. And you will see first - normal addons behaviour (pls see 1st screenshot)
3. If you do it again - then you'll see a strange addon's view (2nd screenshot)

**Expected behavior**
Expected is to always show as for the first time after installing/reactivating the addon

**Screenshots**
Pls see above

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Anki version (Version ⁨2.1.49 (dc80804a)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2)

**Comment by fonol** [comment]
Hi, I see you are using some other edit add-ons (multi-column?). Does the error occur when disabling these?
In general, I don't think the add-on version on Ankiweb will run on 2.1.49 (there have been lots of changes to the editor).
2.1.50 (which can be tested in beta) will introduce even more breaking changes, and that is why it is the version that I currently test against. Which means I will wait until 2.1.50 is released, and then update the add-on on Ankiweb.

**Comment by camerooncameroon** [comment]
Thanks! Yes I disabled all addons and then tried to run your addon with the same results.
Good luck in coding the new version for the 2.1.50 Anki Desktop, we'll be waiting to try ))

**Comment by camerooncameroon** [comment]
I found the cause of the error, it's the conflict with the addon Customize Editor Stylesheet.
After disabling, there's no damage to the SIAC addon UI

**Comment by fonol** [comment]
Thanks for investigating! :)
