### ISSUE TITLE
Addon stops anki browser shortcut "Ctrl+F" from working

### ISSUE THREAD

**Issue by Afoo133** [fonol/anki-search-inside-add-card#303]
Usually when looking at a card from the anki browser, you can press "Ctrl+F" to focus directly on the search bar, selecting any text that's there (image below). However, after installing the addon, this is not possible anymore. I'm really used to this shortcut, but I've lost access to it since I recently started to use your addon so much that it is impossible for me to unninstall it (thank you for your AMAZING work!).

Weirdly though, if you select mutiple cards on the anki browser, or none at all, the shortcut starts to work again! The bug only occurs if you have specifically one card selected (which unfortunately happens to be 99% of the time lol). It does look like a very simple bug (maybe some sort of shortcut interference on browser?)

Edit: _issue still persists if "anki-search-inside-add-card" is the ONLY addon running._
Another edit: _changing the "toggleShortcut" on config.json to something other than "Ctrl+F" does nothing! Also, issue still persists._
More edits: Anki version is 2.1.35.

![image](https://user-images.githubusercontent.com/89617148/143427069-89aa1de0-6d03-4325-8740-9bd62fbb5fcb.png)

**Comment by fonol** [comment]
Hi, 
sorry for the late response. The issue should be fixed with the next version (which will come out with Anki 2.1.50). But since Anki underwent so many changes internally with each of the last versions, I do not longer target older versions, so you would have to update to 2.1.50 then.

**Comment by Afoo133** [comment]
Thanks you so much friend! Appreciate it 💕
