### ISSUE TITLE
Option to disable timeline

### ISSUE THREAD

**Issue by omega3** [fonol/anki-search-inside-add-card#31]
Can you please add option in config to disable timeline?

> 04-07-19: + added a small timeline to the bottom, which displays each day of the year in a color depending on how many cards where added that day, still a bit rough, but it works. You can hover to see the cards on each given day.

**Comment by fonol** [comment]
Yea maybe, I'm curious, does it work for you?

**Comment by omega3** [comment]
Yes. It looks it like this:
https://imgur.com/Sv7RJPz
https://imgur.com/nLxq9UH

**Comment by fonol** [comment]
I think the next update will just be some more config options, I will include it.

**Comment by fonol** [comment]
Option is now in config, also available through the _styling_ dialog.
