### ISSUE TITLE
Feature request: Copy whole page to Image Occlusion

### ISSUE THREAD

**Issue by jmacmusic** [fonol/anki-search-inside-add-card#312]
Currently, you use the snip tool to copy a portion of a page as a screenshot to Image Occlusion. For my purposes, this generally leaves me with either an image whose resolution is too low, or which has to be split into chunks which hampers the learning process somewhat. Would it be possible to implement the option of exporting an entire page at full resolution to Image Occlusion? It is for learning sheet music.

Thanks :)

**Comment by fonol** [comment]
Hi, you should allready be able to do that, using

![image](https://user-images.githubusercontent.com/22644769/158681400-2a774c07-0400-4e1a-acaa-915d0e29f847.png)

"Page Snapshot" at the top

**Comment by jmacmusic** [comment]
It was under my nose the whole time! Thanks, works perfectly :)
