### ISSUE TITLE
Not compatible with 2.1.50

### ISSUE THREAD

**Issue by phonzia** [fonol/anki-search-inside-add-card#319]
**Describe the bug**
Start failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/3022520/164952761-b0a98f4c-895f-47fb-b479-468ccc8a3049.png)

**Environment (please complete the following information):**
 - OS: macos
 - Anki version : 2.1.50

**Comment by basilpapadimas** [comment]
<img width="448" alt="Screenshot 2022-04-27 at 2 37 02 PM" src="https://user-images.githubusercontent.com/28255565/165510047-60b23fe9-d843-4c7d-bbf7-557a13cd2561.png">

Just reproduced this on a clean Anki install on macOS Monterey on M1. Anki version specifics (this is the version for Apple Silicon):
Version ⁨2.1.51 (cf78a555)⁩
Python 3.9.7 Qt 6.2.3 PyQt 6.2.3

**Comment by fonol** [comment]
Hi, I will publish an update compatible with 2.1.50+ in the next weeks (the current version here on Github should already be largely compatible, but needs some more testing).

**Comment by douhan** [comment]
Still not fixed, Is there a way to go around that error? [this](https://github.com/fonol/anki-search-inside-add-card/pull/320) didn't work for me :(

**Comment by douhan** [comment]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Searching PDF Reading  Note-Taking in Add Dialog⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 244, in loadAddons
    __import__(addon.dir_name)
  File "/home/douhan/.local/share/Anki2/addons21/1781298089/__init__.py", line 4, in <module>
    from . import src
  File "/home/douhan/.local/share/Anki2/addons21/1781298089/src/__init__.py", line 612, in <module>
    init_addon()
  File "/home/douhan/.local/share/Anki2/addons21/1781298089/src/__init__.py", line 121, in init_addon
    aqt.editor._html += """ <script> document.addEventListener("keydown", function (e) { if (typeof (globalKeydown) !== 'undefined') globalKeydown(e); }, false); </script>"""
AttributeError: module 'aqt.editor' has no attribute '_html'
⁩
