### ISSUE TITLE
under Anki 2.1.53 an 2.1.54 the enabled plugin doesn't show up

### ISSUE THREAD

**Issue by karolszk** [fonol/anki-search-inside-add-card#330]
Hello,

A couple of days ago I have successfully installed plugin (1781298089) and just started using it.
Today I have noticed that plugin doesn't show up. I double check the settings. Plugin is enabled.
Is it true that actually plugin requires <= 2.1.52?
I have checked the newest version 2.1.54 -> also without success.

Environment: I am using Anki on Linux with Qt6.

Thank you. By the way: great plugin! 

Karol

**Comment by kvn1351** [comment]
Because of #324.
