### ISSUE TITLE
Version Incompatibility - Did I just lose all my pdf notes?

### ISSUE THREAD

**Issue by MNastri** [fonol/anki-search-inside-add-card#331]
(Sorry if I'm not asking this in the appropriate place)

I started Anki and noticed that the menu for the addon at the top was missing.
I checked that the addon was now disabled for my Version ⁨(2.1.49), but it was working fine on 25-jun-2022. 
I tried but it won't reinstall due to this version incompatibility.
Visiting the addon page says that it doesn't support my Anki version, even though it was working fine just two days ago 

My issue:
Did I just lose everything/some of the things I had with the addon (the pdf notes, their priorities, schedules, bookmarks, etc.)?
If recovery is possible:
Can I just upgrade Anki, reinstall the addon and get everything back? 
Or should I downgrade Anki first then install the addon to get everything back?

P.S.:
I have just came back to Anki (on the 25-jun to be exact) after a few months of absence (college), and can't upgrade it right now. I don't want to lose everything I've done so far with this addon.
By the way, **I never upgraded my Anki** so that I could keep using this addon and now it says that this Anki version is incompatible, this is really weird...

**Comment by fonol** [comment]
Hi, maybe I accidentally set the add-on compatibility for the last version to 2.1.48 max when it should have been 2.1.49. I set it to .49 now, so you should be able to use it again. No data should be lost.

**Comment by MNastri** [comment]
It's working again. I appreciate your help and the effort put on the addon.
Sorry for the delay in reverting back to you
Again, thank you for the addon. It is awesome
