### ISSUE TITLE
Search for numbers?

### ISSUE THREAD

**Issue by galantra** [fonol/anki-search-inside-add-card#36]
The add-on excludes numbers (1234…) from the search, am I right?
I study law and thus I often use numbers of section from legal codes as an abbreviation for a bigger concept.
Would searching for numbers be hard to implement?

**Comment by fonol** [comment]
This is on my list. Cannot tell you when exactly it will be included though.

**Comment by fonol** [comment]
Should work with the newest update:
Single numbers (e.g. "4") are ignored
Numbers longer than that have to match exactly.

**Comment by galantra** [comment]
Yes, it does! 🔢 
Good way of implementation.
For me, search time is still not significantly noticiable.
