### ISSUE TITLE
Error: no such table: notes_content

### ISSUE THREAD

**Issue by galantra** [fonol/anki-search-inside-add-card#37]
I downloaded the last update and received this when I tried to add a note:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.15 (6661ba8a) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\webview.py", line 322, in handler
  File "C:\Users\Jo\AppData\Roaming\Anki2\addons21\516643804\main.py", line 177, in oncallback
    runHook("loadNote", self)
  File "anki\hooks.py", line 29, in runHook
  File "C:\Users\Jo\AppData\Roaming\Anki2\addons21\1781298089\__init__.py", line 602, in onLoadNote
    printStartingInfo(editor)
  File "C:\Users\Jo\AppData\Roaming\Anki2\addons21\1781298089\web.py", line 635, in printStartingInfo
    html += "<br/>Index contains <b>%s</b> notes." % searchIndex.get_number_of_notes()
  File "C:\Users\Jo\AppData\Roaming\Anki2\addons21\1781298089\fts_index.py", line 417, in get_number_of_notes
    res = conn.cursor().execute("select count(*) from notes_content").fetchone()[0]
<class 'sqlite3.OperationalError'>: no such table: notes_content

**Comment by fonol** [comment]
Hm, that is really weird, I don't have an explanation ready for that, I uploaded a slightly modified version, but no guarantees. If it still doesn't work, you could delete the "search-data.db" file in the addon's folder, and restart Anki.

**Comment by galantra** [comment]
The slight modification has indeed solved the issue!

**Comment by galantra** [comment]
The issue reappeared with the most recent update.
I deleted search-data.db and thus solved it.
