### ISSUE TITLE
Is it possible to make the addon compatible with version 2.0.X?

### ISSUE THREAD

**Issue by Cardosaum** [fonol/anki-search-inside-add-card#4]
Hello, I saw the addon on reddit and found it very interesting, but I can not use it for incompatibility... (many addons I use are still restricted to version 2.0.X so I opted not to upgrade the program)

Anyway, congratulations to the initiative, I hope you succeed in this project. and thank you for sharing with the community!

**Comment by fonol** [comment]
I don't know how much effort exactly would be needed to do that, so I can't promise anything, but I will definitely look into it as there are quite some people like you that are still using 2.0

**Comment by fonol** [comment]
Closed as official support has ended for 2.0, so there is much less incentive to port.
