### ISSUE TITLE
Search for morphemes instead of words

### ISSUE THREAD

**Issue by galantra** [fonol/anki-search-inside-add-card#41]
Hi, one suggestion for the search in add-on mode.

I see from you screenshots in the description that you know German. The add-on mode works magnificently in English where you don't have a lot of suffixes or prefixes. When you search for "Buch" however, it won't show you "Bücher". I hope it can be modified so as to take into account grammatical inflections and then show all forms related to a morpheme. Preferably, ignoring similar morphemes' forms – in our case, "Buchen" for example.

Maybe it can be done through modifying the synonyms function. Manually entering a list of all inflections of all words would of course take more than a lifetime.

A few days ago, I saw on GitHub that someone had implemented some third person's software in their program. He seemed to use it to take into account inflections. However, I don't remember the name and can't find it again. The software's name began with "morph"…, I think. 
It was not MorphMan. The Morphman documentation on GitHub however talks about "morpheme-splitting-tools" (which I've not read before but just discovered today). Maybe we can follow that trace.

**Comment by fonol** [comment]
Not easily possible to do I am afraid. 
To reduce German words like "Bücher" and "Buches" to the same base form, one would have to use a stemmer or lemmatizer. That would require using some third party NLP module like NTLK, and there would have to be a model/implementation for each supported language. Now just adding NTLK would likely triple the size of the add-on and shipping third party libraries with Anki add-ons is a major nightmare. I actually once tried to include NTLK in some other add-on, but rage-quit at some point. In fact, SQLite FTS comes with a simple stemmer (Porter). That one works best for english, e.g. it would have trouble with German umlauts, for other cases it might actually improve the recall.
I guess it would reduce both "Buchen" and "Buches" to "Buch". If that is an improvement, you decide.
You can try out the Porter stemmer there:
https://text-processing.com/demo/stem/ 
 I know what you are getting at, and it has been bugging me too, but right now it just seems like it would require too much work. 
If you don't mind some python, I suggest you try out the Porter stemmer.
https://sqlite.org/fts5.html 
There is a section about using the stemmer, in fact you would only have to change a single line in fts_index.py:
`create virtual table notes using fts5(nid, text, tags, did, source, mid, refs)
`
to 
`create virtual table notes using fts5(nid, text, tags, did, source, mid, refs,  tokenize = porter)`
(You would have to select the line depending on whether you use FTS 3, 4 or 5)

**Comment by galantra** [comment]
Thank you for your answer! It is detailed and well-understandable.

"Stemmer" is probably the word I read in that project. I found [https://github.com/lovac42/Wordsworth](https://github.com/lovac42/Wordsworth) in relation to stemmers and Anki. The API he uses is Porter2-stemmer by Evan Dempsey. I don't know if this brings any benefit to your project but I don't want to hide it from you.

I totally see that a full implementation of NLTK would not be sensible. Especially since looking for a specific set of letters can already be done in browser mode.

I'm not familiar with python but I read up about the stemmer and added 

> , tokenize = porter

to each row in the code, like you suggested. Restarted Anki. The add-on didn't find "lead" when I put in "leading", not "exam" from "examination", not "eat" from "eaten".

I do have 

>    "useFTS": true,

Am I unintendedly skipping a step?

**Comment by fonol** [comment]
Just a guess: Probably the index did not rebuild (since there were no changes in your collection since the last indexing). You can force it under Info&Settings

**Comment by galantra** [comment]
Yep, you guessed right there! This is already a huge progress by no effort :D

**Comment by fonol** [comment]
There is now a config option that you can set to true: _usePorterStemmer_ :)
