### ISSUE TITLE
Enhancement suggestion for Cloze generator

### ISSUE THREAD

**Issue by cstandi** [fonol/anki-search-inside-add-card#43]
When adding cards it automatically selects the deck that is in the add card window. It would be great if it did this with the tags and note type fields as well. This would make adding the Cloze cards much more efficient.

The other option that I was thinking is that the Cloze generator could have an option to send to text field for adding B,I,U words. Similar to how you have it set for the IMG capture tool. Then I could grab the text I need and it would already have all of its Cloze deletions and the pictures and then hit add.

**Comment by fonol** [comment]
> It would be great if it did this with the tags and note type fields as well
I get the issue with the tags, but I don't understand the part about note types. Could you elaborate?

The send to text field option could be interesting, I will look into it.

**Comment by cstandi** [comment]
This new update is awesome. I pretty much only use this add on now when adding cards!
