### ISSUE TITLE
Image selector not adding pictures

### ISSUE THREAD

**Issue by cstandi** [fonol/anki-search-inside-add-card#44]
Just wanted to say that the send to edit field of the last couple add ons is incredible! It is such a great time saver. 
I did notice that when I send text to the edit field that unless I click in the field to add changes it will not read as any text being there (I get an "empty front field" notice). With your Cloze generator I almost never need to edit the field with text I pretty much just add pictures in the extra field. 
The other issue I've noticed is when I add a picture using the image snipping tool that it will not save when I add the card unless I edit the field after I add the card (ie add Cloze deletion around it or text below it. Since I normally do not do this it is prohibiting me from using this function.

Thank you for all your hard work and I hope that this helps to improve this awesome add on.

**Comment by fonol** [comment]
Good catch. I think it was the same problem for both, the image and the cloze: The field content really only gets internally updated when you stop typing in the field. 
You can try out the new version.
