### ISSUE TITLE
Throwing error message at launch with 2.1.17

### ISSUE THREAD

**Issue by Cupbox** [fonol/anki-search-inside-add-card#46]
Anki 2.1.17 (81bdd860) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=?

C:\Users\John Smith\AppData\Roaming\Anki2\addons21\1781298089\src\notes.py:207: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  conn.execute("delete from marks where nid = %s and page %s and marktype = %s" (nid, page, mark_type))

**Comment by fonol** [comment]
Missed a '%'. Updated version is up.

**Comment by Cupbox** [comment]
Fixed on my end. Thanks.
