### ISSUE TITLE
Preparing index

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#5]
I have about 50,000 cards and always enter the Anki, apparently it recalculates the indexes, not even creating any new cards. this process is time consuming.

Is this step really necessary? should not occur only once and then be just incremental?

![image](https://user-images.githubusercontent.com/42243532/54116225-115a5480-43cd-11e9-82c3-82bc054dc030.png)

**Comment by fonol** [comment]
This is on my list too, meanwhile, you could try out useFTS in the config, I noted it is a bit faster in index creation.

**Comment by cjdduarte** [comment]
I'll try. What would that useFS be? I also noticed a delay in opening Anki.

**Comment by fonol** [comment]
Some other type of reversed index, which comes with many sqlite distributions. By default, the python package "Whoosh" is used for that.

**Comment by cjdduarte** [comment]
Thank you for the explanation
