### ISSUE TITLE
Feature suggestion: Show deck

### ISSUE THREAD

**Issue by galantra** [fonol/anki-search-inside-add-card#50]
As far as I know, there is no way to see in your add-on which deck a card belongs to.

I can think of 3 ways. One would be sufficient for me personally.

1. In the "info" pop-up
2. somewhere around the border of the cards in the add-on's panel (where you have info, tags, edit, magnifying glass, etc.)
3. upon clicking "edit" in the add-on's panel, there could be buttons to change the deck and the note type. like in the normal primary edit window

**Comment by fonol** [comment]
1. Should be doable quickly
2. Rather not, because of space (e.g. with long decknames, subdecks etc.)
3. That would require some work, so rather not

I will look to add 1. in some of the next updates.

**Comment by fonol** [comment]
Decks are shown in the info modal now, so I'm gonna close this one.
