### ISSUE TITLE
bug report: the pdf reader always has focus

### ISSUE THREAD

**Issue by agerhbour** [fonol/anki-search-inside-add-card#57]
If you press ctrl+left/ctrl+right while the cursor is in one of the text fields in add card, the pdf window still has focus and continues to move.

**Comment by fonol** [comment]
I try to include a fix in the next update.

**Comment by fonol** [comment]
Should be fixed.

**Comment by agerhbour** [comment]
I know you closed this a loong time ago, but this doesn't actually seem to be fixed :(

**Comment by fonol** [comment]
Hi, there will be some improvements to shortcut management with the next update, so I would wait and see if the issue persists then :)
