### ISSUE TITLE
Get an issue when trying to create a card

### ISSUE THREAD

**Issue by alih1029** [fonol/anki-search-inside-add-card#59]
Debug info:
Anki 2.1.19 (3c8690ae) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
Traceback (most recent call last):
File "C:\Users\user\AppData\Roaming\Anki2\addons21\1781298089\src\index\fts_index.py", line 267, in printOutput
self.output.print_search_results(result["results"], stamp, logging = self.logging, printTimingInfo = True, query_set=query_set)
File "C:\Users\user\AppData\Roaming\Anki2\addons21\1781298089\src\output.py", line 312, in print_search_results
cmd = "setSearchResults(`%s`, ``, null, page=%s , pageMax=%s, total=%s, cacheSize=%s, stamp=%s, printTiming=%s);" % (html, page, pageMax, len(notes), len(self.previous_calls), stamp, timing)
UnboundLocalError: local variable 'timing' referenced before assignment

**Comment by fonol** [comment]
Thanks, this occurs when "HideSidebar" is true, I updated the add-on to include a fix.
