### ISSUE TITLE
"Preparing index" frozen

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#6]
If you start typing text in the field before the "Preparing index" finishes, it freezes.

**Comment by fonol** [comment]
will look into it, thanks!

**Comment by cjdduarte** [comment]
There was a performance improvement at that point. It does not seem to be a problem anymore.

**Comment by cjdduarte** [comment]
intermittently, this problem seems to continue.

![image](https://user-images.githubusercontent.com/42243532/54275947-c1b18f80-456a-11e9-9220-dd5e9cedf647.png)

**Comment by fonol** [comment]
Unfortunately I cannot reproduce this on my machine. If I type while the index loads, nothing happens, (well, the "searching" appears, which is annoying), and as soon as the loader disappears, I can search

**Comment by fonol** [comment]
If the "searching" status freezes, then a note is under the results which either destroys the html or, more likely, the javascript into which it is inserted. I have catched and corrected two cases today, one was ` backticks in the note text, second \ backslash in combination with some characters. So it could be, that you typed a term which returned results containing either of these, and this prevent further execution of javascript, which should have hidden the loader. just a theory

**Comment by fonol** [comment]
so if you type in a search term, and the "searching" freezes, maybe try to locate the card among the results that contains many special characters, would be really helpful for me

**Comment by cjdduarte** [comment]
This was my test before the recent changes you made. I will close again and if the error occurs again and can isolate the card, I reopen so that you can evaluate.

Thank you.
