### ISSUE TITLE
Images in the "Note-Taking" are deleted after Anki is close. 

### ISSUE THREAD

**Issue by Uitalo** [fonol/anki-search-inside-add-card#63]
I noticed that the images are being deleted after closing Anki.

![image](https://user-images.githubusercontent.com/13296083/75173040-0519f500-570d-11ea-88f4-7f03b2ac6f08.png)

Copying and pasting as html, I realized that a reference is made to an Localhost file:

![image](https://user-images.githubusercontent.com/13296083/75174026-950c6e80-570e-11ea-9c94-3702b29d4cbc.png)

![image](https://user-images.githubusercontent.com/13296083/75174958-3ea02f80-5710-11ea-8532-50fbbd217914.png)

**Comment by fonol** [comment]
Image handling doesn't really work atm, I guess I should probably write that down somewhere.
