### ISSUE TITLE
Not working after 01-03-20 upgrade 

### ISSUE THREAD

**Issue by SimpNation2** [fonol/anki-search-inside-add-card#66]
I'm having this issue after upgrade:

![image](https://user-images.githubusercontent.com/61680949/75653400-472ac580-5c3c-11ea-83a6-b87aac8539ed.png)

My Anki version is 2.1.11 (3cf770c7)
Qt 5.12.1 PyQt 5.11.3

Before upgrade it was running fine.

By the way, consider upgrade pdf reader with some tools like highlight text, it would be incredible!
Also, when I edit some card directly from add-on and I accidentally press on ESC, it doesn't ask if I want to prevent or save the changes. Could you improve that? Last thing, the search bar isn't that accurate and sometimes doesn't bring the cards with most keywords, why does that occurs?
Thank you.

**Comment by fonol** [comment]
Hi, sorry, I forgot to specify that the new version uses Anki's new hooks, so it needs the newest Anki version (2.1.20) to work.
About the ESC issue, I will look if I can change that.
Do you mean the search bar in browser or in add-on mode? If add-on mode, what index are you using? (You can see that in Settings & Info -> Info)

**Comment by Uitalo** [comment]
Hi @fonol 
The shortcut Ctrl + F stopped working in the last update.

**Comment by fonol** [comment]
Hm, it works for me, I tested it on two machines. What does your config say for "toggleShortcut"?
Did you install any other editor add-ons recently? Does Ctrl+o work for you?
Maybe there try some other value for "toggleShortcut" (there might be a aconflict with another add-on shortcut=.

**Comment by galantra** [comment]
How do you think about adding a legacy version that supports the old hook system which was used prior to Anki 2.1.20?
Ankiweb allows uploading more than one version under the same number, as seen [here](https://ankiweb.net/shared/info/679615590) and [here](https://ankiweb.net/shared/info/1918380616), for example.

**Comment by Uitalo** [comment]
@fonol  I haven't added any Add-Ons recently, I just updated some that I had, tried a series of shortcuts, but with no positive result, I don't know what happens.

I tried to search for "Ctrl + F" in the add-ons folder as well and changed all possible conflicts, but also without success.

**Comment by fonol** [comment]
Hm, I guess even if you didn't add any other add-ons recently, the change in how this add-on registers its shortcuts might still be the reason there is now a conflict. Does it work if you disable your other add-ons?
If you want to help me, you could open the Add dialog, then switch to the main dialog, open the debug console (https://apps.ankiweb.net/docs/manual.html#debug-console), paste the following, and hit cmd/ctrl + enter:

```
from aqt import gui_hooks
print(gui_hooks.editor_did_init_shortcuts._hooks)

shortcut = next(s for s in aqt.dialogs._dialogs["AddCards"][1].findChildren(QShortcut) if s.key().toString() == "Ctrl+F")
print(shortcut)
```

I would be interested in the output.

@galantra Maybe when I got some time. Any particular reason you prefer to stay on older versions?

**Comment by fonol** [comment]
I added an update, which should show an error message if something goes wrong in the javascript part of the toggle shortcut, please report if something shows up if you try the shortcut with the update.

**Comment by galantra** [comment]
> Any particular reason you prefer to stay on older versions?

It was because two add-ons didn't work, Night Mode and Zoom 2.1.

However I installed the newly released [https://ankiweb.net/shared/info/538879081](Anki Zoom) just today and switched to Anki 2.1.20. There, I use the native night mode.

As a consequence, I think I won't ever use the older version anymore. Thus you don't have to make a version as far as I'm concerned.

I hoped it would just require uploading an older version of the code.

**Comment by Uitalo** [comment]
@fonol It returned to work after the last update. I had been trying to disable recently updated add-ons by moving them to a different folder, but I was also unsuccessful. Do you want me to restore the previous version and take this test?

**Comment by fonol** [comment]
@Uitalo it is fine, I am happy as long as works for you.
@galantra I guess most users will eventually move to 20 or later anyway, just for the built in night mode, so I guess there is no real need.
