### ISSUE TITLE
Losing PDFs when upgrading to 2.1.21 beta 3

### ISSUE THREAD

**Issue by silentcicada1** [fonol/anki-search-inside-add-card#67]
All pdf's in the notes section are gone after updating. No errors but all notes and associated tags and bookmarks are nowhere to be seen.

**Comment by fonol** [comment]
Hm, that shouldn't happen. I checked what is changed in beta 3, and there don't seem any breaking changes. Where did you save the notes, i.e. what did it say in the "Info" dialog about your path to the note db file? And what does it say now? Is the file ("siac-notes.db") there when you check it yourself?

I just upgraded from beta 2 to beta 4, the release version, and no problems occured to me.

**Comment by silentcicada1** [comment]
I downloaded beta 4 instead of beta 3 and it worked. Thanks
