### ISSUE TITLE
Question about profiles

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#7]
I have about 4 profiles in Anki.
How does it index when between accounts? Does it erase everything and start again?

**Comment by fonol** [comment]
Uh, I haven't tested for this case at all, I only have one profile myself, I will look what happens / what should happen in this case.

**Comment by cjdduarte** [comment]
OK. Tanks.

**Comment by cjdduarte** [comment]
Have you been able to evaluate this case? As I alternate between profiles to study, I'm concerned that the add-on is deleting or blending indexes.

**Comment by fonol** [comment]
I don't have multiple profiles to test, but the addon builds the index directly after the profile is loaded (hooked at "onProfileLoaded"). So  in theory if you switch your profile, this should trigger a rebuild of the index.

**Comment by cjdduarte** [comment]
OK, about rebuilding the index, there could be a button so you can trigger it manually. I say this because of this explanation:

> 2. Cards added in the current session are not in the index until you restart the program.

**Comment by fonol** [comment]
Yea, that is on the list. I am not sure whether it will be a rebuild button or simply an automatic rebuild after you have added a note, but something needs to be there

**Comment by cjdduarte** [comment]
OK, I'll close this topic.
