### ISSUE TITLE
Copy-Paste not working propperly

### ISSUE THREAD

**Issue by IIPatternII** [fonol/anki-search-inside-add-card#74]
- System: macOS 10.14.5
- Anki: 2.1.23

When copying and pasting text from the pdf to a field, the text is copied without color, and the background is in the same color as the pdf view.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/48034748/77356486-29c1b680-6d25-11ea-878c-951967968dfc.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48034748/77356615-6ee5e880-6d25-11ea-86c7-00229a35da6d.png">

Current solution: With every paste, I change the text and background colors.

**Comment by fonol** [comment]
Hi, have you tried checking the "Paste without shift strips formatting" option in Anki's preferences dialog?

**Comment by IIPatternII** [comment]
That solved the issue! Thank you kind sir!
