### ISSUE TITLE
Not working after today's update

### ISSUE THREAD

**Issue by succil** [fonol/anki-search-inside-add-card#83]
Anki Version 2.1.22 (0ecc189a)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
![issue](https://user-images.githubusercontent.com/63019606/78183681-b283d500-743e-11ea-86f1-f85850d071eb.png)

Missing all search box and stuff..

**Comment by succil** [comment]
After clicking on world icon, all I got is a Google page. 

![issue 2](https://user-images.githubusercontent.com/63019606/78183901-068eb980-743f-11ea-96d9-f51af2494530.PNG)

**Comment by fonol** [comment]
I think I uploaded the wrong addon with the last update. Should be fixed now, so please update again.

**Comment by succil** [comment]
Thank you, everything is working fine so on.

**Comment by fonol** [comment]
Your addon's notes are still there?

**Comment by succil** [comment]
Yes they still. Even though when you released 01-03-20 update, I lost my personal notes created inside the app (I mean, those notes that are independent of Anki's notes), today everything still here 👍
