### ISSUE TITLE
Korean search doesn't work properly

### ISSUE THREAD

**Issue by minbec** [fonol/anki-search-inside-add-card#88]
Hello, I was trying out the new version and I noticed that when you are searching for a korean word it doesn't show up. Only single characters can be found. I guess this is because korean words consist of syllable blocks and not just single characters. For example if you search for ㅎ it will only show cards which use this character on its own. Which means that syllable blocks like 한 won't be found. Are you planning to fix this? Thank you for your hard work!

**Comment by fonol** [comment]
Hi, I'm afraid that is not really possible, it is the same for Chinese characters, you can only search for exact characters and not for parts of compounds.

**Comment by minbec** [comment]
Sorry, I think I didn't explain that very well! I don't want to search for parts of compounds I was thinking of searching for syllable blocks like 한. But if you type in 한 words with 한 won't show up. I took a look at your code and I saw that you indeed used \u3131-\uD79D for the characters - so that's why I am wondering why the search doesn't work. Do you have an idea? Thank you for the fast answer.

**Comment by fonol** [comment]
<img width="619" alt="Unbenannt" src="https://user-images.githubusercontent.com/22644769/80845602-07676680-8c0a-11ea-82ac-b022d5066d6d.PNG">

I am not really familiar with korean language structure, so maybe I am missing something.
I downloaded a korean deck (https://ankiweb.net/shared/info/3614346923), and then searched for the character you mentioned in your last comment: 한.

**Comment by minbec** [comment]
I just deinstalled and reinstalled the addon and now it works fine for me too. How strange that it didn't work in the first place. Thank you for your help! Have a nice day.
