### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by cjdduarte** [fonol/anki-search-inside-add-card#9]
My Anki is in PT-BR. We use ç, á, ô, ã, etc ...
It looks like the keywords screen is deleting these letters. They do not appear.

![image](https://user-images.githubusercontent.com/42243532/54117280-20da9d00-43cf-11e9-8aae-ff49327493f2.png)

**Comment by fonol** [comment]
regex for word boundaries only looks for a-zöäü currently, will look into it

**Comment by fonol** [comment]
Should be better now, but still not working 100% for me. Btw, have you edited your stopwords list in the config? Because I see "que" in your screenshot. If not, you should absolutely do, it really makes searching more accurate (and faster)

**Comment by cjdduarte** [comment]
> Should be better now, but still not working 100% for me. Btw, have you edited your stopwords list in the config? Because I see "que" in your screenshot. If not, you should absolutely do, it really makes searching more accurate (and faster)

Yes. I'm creating my list. I was just waiting for those corrections. This problem has been corrected.
