### ISSUE TITLE
Recognise that e.g. and i.e. is not the end of a sentence when generating clozes.

### ISSUE THREAD

**Issue by An-png** [fonol/anki-search-inside-add-card#96]
The generate cloze button considers a full stop / period as the end of the sentence. However, sometimes abbreviations such as e.g. and i.e. are used. Could the addon recognize if full stop is immediately followed by "g." or "e." for example? That way it knows it is probably a common abbreviation .

**Comment by fonol** [comment]
Should be done with the newest update.

**Comment by An-png** [comment]
> Should be done with the newest update.

By this do you mean that the code to fix this issue already exists or that you will fix this bug soon?

**Comment by fonol** [comment]
It is already in the newest version in Ankiweb (and on Github).

**Comment by An-png** [comment]
Why is the ankiweb version the develop branch? At that point doesn't the develop branch simply serve the purpose that the master branch is supposed to?

**Comment by fonol** [comment]
At this point it is not really needed. I branched at a time when I made heavy changes and wanted to keep a working branch for quick fixes, plus I am simply used to have master + dev from other projects.
