### ISSUE TITLE
Incrementally reading text notes.

### ISSUE THREAD

**Issue by An-png** [fonol/anki-search-inside-add-card#99]
Currently, you can only sort of do "incremental reading" on PDFs. This is because you can mark a page as being "read".

Could something like this be done with text notes? For example, they could be split up by section headers instead of by pages, and you can highlight, read, and make cards of sections and then mark that section as read.

This header extraction thing could work somewhat like this: https://youtu.be/DoQoeK53bP8?t=48  (timestamp: 50 seconds).

**Comment by fonol** [comment]
Hi, as this is kinda related, please see my answer to your other issue!

**Comment by An-png** [comment]
The reason I think text notes should be able to be incrementally read is because you can manipulate and split up text notes much better than PDFs. [For example, this Wikipedia article is split into chunks in Supermemo incremental reading.](https://www.youtube.com/watch?v=DoQoeK53bP8)
